### ISSUE TITLE
Play/ Pause restarts the current song

### ISSUE THREAD

**Issue by PostsDesert** [stevenleeg/geemusic#10]
Danondso [on his repo](https://github.com/Danondso/GooglePlayEchoMusicService/commit/3cc30a08b2027595db38452cfa768fc412c3bf59) had been working on fixing this issue. He was using the offset key to start the song close to where you pause it. I was wondering if that would be something we could merge into Gee Music.

**Comment by Danondso** [comment]
I think I might have found a workaround for it now, I've just committed the change to my geemusic fork. I'm grabbing the song offset from the context response and calling play() while passing in the stream_url and the offset. Once and a while it doesn't seem to pick it back up and you have to call stop and then resume again. I'm not sure why that's the case though right now.

**Comment by stevenleeg** [comment]
@Danondso That's awesome if you have something with a basic fix for this! Feel free to open a PR early if you'd like, that way we can all look/discuss the solution.

**Comment by Danondso** [comment]
Sure thing! Once I get preliminary testing out of the way on my end I'll make the pull request.

**Comment by PostsDesert** [comment]
Just adding my results in. When you Pause and resume for some reason it does not always resume the first time. However saying resume again almost always resumes the song correctly.

**Comment by stevenleeg** [comment]
This issue should be resolved by #13, I just want to do some testing later tonight before I merge.

**Comment by stevenleeg** [comment]
going to close this, as discussion should be moved to that PR.
