### ISSUE TITLE
No music after initial response

### ISSUE THREAD

**Issue by fatguy108** [stevenleeg/geemusic#102]
No matter what I request, it seems Alexa is never actually able to pull a song and play it back. It's worth noting that I'm mildly clueless on how to actually get any valuable debug info. 

Also, I've tried this on both a virtual machine running withing windows and a direct Ubuntu Server install, with no luck from either. Do you think it could have something to do with my network? 

![image](https://user-images.githubusercontent.com/29350675/27258146-894dfcb6-53a7-11e7-90a6-829c778391c9.png)

**Comment by mymac80** [comment]
I have the exact same issue. Here's my response object: `{
  "version": "1.0",
  "response": {
    "outputSpeech": {
      "text": "Playing Despacito by Luis Fonsi",
      "type": "PlainText"
    },
    "card": {
      "text": "",
      "title": "Playing Despacito by Luis Fonsi",
      "image": {
        "smallImageUrl": "https://lh3.googleusercontent.com/QghVaMl-X73cK10Fgr9zPE2xRwTO5wv2pdCCN9ySwzCmn1OI-ghGnqRs4w7YetEbhqL2drWK_n0",
        "largeImageUrl": "https://lh3.googleusercontent.com/QghVaMl-X73cK10Fgr9zPE2xRwTO5wv2pdCCN9ySwzCmn1OI-ghGnqRs4w7YetEbhqL2drWK_n0"
      }
    },
    "speechletResponse": {
      "outputSpeech": {
        "text": "Playing Despacito by Luis Fonsi"
      },
      "card": {
        "text": "",
        "image": {
          "smallImageUrl": "https://lh3.googleusercontent.com/QghVaMl-X73cK10Fgr9zPE2xRwTO5wv2pdCCN9ySwzCmn1OI-ghGnqRs4w7YetEbhqL2drWK_n0",
          "largeImageUrl": "https://lh3.googleusercontent.com/QghVaMl-X73cK10Fgr9zPE2xRwTO5wv2pdCCN9ySwzCmn1OI-ghGnqRs4w7YetEbhqL2drWK_n0"
        },
        "title": "Playing Despacito by Luis Fonsi"
      },
      "directives": [
        {
          "playBehavior": "REPLACE_ALL",
          "audioItem": {
            "stream": {
              "token": "62386013-da75-4fd4-95e9-xxxxxxxxxxxxx",
              "url": "https://myid.ngrok.io/alexa/stream/Tdembynodmfvcsy4m2nk7uv5izq",
              "offsetInMilliseconds": 0
            }
          }
        },
        {
          "template": {
            "image": {
              "sources": [
                {
                  "url": "https://lh3.googleusercontent.com/QghVaMl-X73cK10Fgr9zPE2xRwTO5wv2pdCCN9ySwzCmn1OI-ghGnqRs4w7YetEbhqL2drWK_n0",
                  "size": "small",
                  "widthPixels": 0,
                  "heightPixels": 0
                },
                {
                  "url": "https://lh3.googleusercontent.com/QghVaMl-X73cK10Fgr9zPE2xRwTO5wv2pdCCN9ySwzCmn1OI-ghGnqRs4w7YetEbhqL2drWK_n0",
                  "size": "large",
                  "widthPixels": 0,
                  "heightPixels": 0
                }
              ]
            },
            "title": "Playing Despacito by Luis Fonsi",
            "textContent": {
              "primaryText": {
                "text": ""
              }
            },
            "backButtonBehavior": "HIDDEN"
          }
        }
      ],
      "shouldEndSession": true
    }
  },
  "sessionAttributes": {}
}`

**Comment by mymac80** [comment]
Solved: Just realized that the APP_URL settings were different in the .env file and the Alexa Dev console config since I had changed it trying to get ngork to work correctly.
