### ISSUE TITLE
Internal Server Error /alexa/stream/

### ISSUE THREAD

**Issue by ajdrausal** [stevenleeg/geemusic#106]
I am running geemusic using docker and I seem to be getting an internal server error.
20:15:51 web.1  | --------------------------------------------------------------------------------
20:15:51 web.1  | DEBUG in selection [/geemusic/geemusic/intents/selection.py:85]:
20:15:51 web.1  | Fetching song pop by None
20:15:51 web.1  | --------------------------------------------------------------------------------
20:15:52 web.1  | 172.17.0.1 - - [09/Jul/2017 20:15:52] "POST /alexa HTTP/1.1" 200 -
20:15:55 web.1  | 172.17.0.1 - - [09/Jul/2017 20:15:55] "GET /alexa/stream/Tfucddjb725el4kb2dtrzfaxk5m HTTP/1.1" 500 -
20:15:55 web.1  | Traceback (most recent call last):
20:15:55 web.1  |   File "/usr/lib/python3.6/site-packages/flask/app.py", line 1994, in __call__
20:15:55 web.1  |     return self.wsgi_app(environ, start_response)
20:15:55 web.1  |   File "/usr/lib/python3.6/site-packages/flask/app.py", line 1985, in wsgi_app
20:15:55 web.1  |     response = self.handle_exception(e)
20:15:55 web.1  |   File "/usr/lib/python3.6/site-packages/flask/app.py", line 1540, in handle_exception
20:15:55 web.1  |     reraise(exc_type, exc_value, tb)
20:15:55 web.1  |   File "/usr/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
20:15:55 web.1  |     raise value
20:15:55 web.1  |   File "/usr/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
20:15:55 web.1  |     response = self.full_dispatch_request()
20:15:55 web.1  |   File "/usr/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
20:15:55 web.1  |     rv = self.handle_user_exception(e)
20:15:55 web.1  |   File "/usr/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
20:15:55 web.1  |     reraise(exc_type, exc_value, tb)
20:15:55 web.1  |   File "/usr/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
20:15:55 web.1  |     raise value
20:15:55 web.1  |   File "/usr/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
20:15:55 web.1  |     rv = self.dispatch_request()
20:15:55 web.1  |   File "/usr/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
20:15:55 web.1  |     return self.view_functions[rule.endpoint](**req.view_args)
20:15:55 web.1  |   File "/geemusic/geemusic/controllers.py", line 9, in redirect_to_stream
20:15:55 web.1  |     stream_url = api.get_google_stream_url(song_id)
20:15:55 web.1  |   File "/geemusic/geemusic/utils/music.py", line 137, in get_google_stream_url
20:15:55 web.1  |     return self._api.get_stream_url(song_id)
20:15:55 web.1  |   File "<decorator-gen-102>", line 2, in get_stream_url
20:15:55 web.1  |     
20:15:55 web.1  |   File "/usr/lib/python3.6/site-packages/gmusicapi/utils/utils.py", line 293, in wrapper
20:15:55 web.1  |     return function(*args, **kw)
20:15:55 web.1  |   File "/usr/lib/python3.6/site-packages/gmusicapi/clients/mobileclient.py", line 371, in get_stream_url
20:15:55 web.1  |     return self._make_call(mobileclient.GetStreamUrl, song_id, device_id, quality)
20:15:55 web.1  |   File "/usr/lib/python3.6/site-packages/gmusicapi/clients/shared.py", line 84, in _make_call
20:15:55 web.1  |     return protocol.perform(self.session, self.validate, *args, **kwargs)
20:15:55 web.1  |   File "/usr/lib/python3.6/site-packages/gmusicapi/protocol/shared.py", line 226, in perform
20:15:55 web.1  |     raise CallFailure(err_msg, call_name)
20:15:55 web.1  | gmusicapi.exceptions.CallFailure: GetStreamUrl: 403 Client Error: Forbidden for url: https://mclients.googleapis.com/music/mplay?opt=hi&net=mob&pt=e&slt=1499631354960&sig=LSMw1iDgasS-SpAZ6gQwQ_B_9lU&mjck=Tfucddjb725el4kb2dtrzfaxk5m&hl=en_US&dv=0&tier=aa
20:15:55 web.1  | (requests kwargs: {'method': 'GET', 'url': 'https://mclients.googleapis.com/music/mplay', 'allow_redirects': False, 'headers': {'X-Device-ID': '0242AC110002', 'Authorization': '<omitted>'}, 'params': {'opt': 'hi', 'net': 'mob', 'pt': 'e', 'slt': '1499631354960', 'sig': b'LSMw1iDgasS-SpAZ6gQwQ_B_9lU', 'mjck': 'Tfucddjb725el4kb2dtrzfaxk5m', 'hl': 'en_US', 'dv': 0, 'tier': 'aa'}})
20:15:55 web.1  | (response was: '<HTML>\n<HEAD>\n<TITLE>Forbidden</TITLE>\n</HEAD>\n<BODY BGCOLOR="#FFFFFF" TEXT="#000000">\n<H1>Forbidden</H1>\n<H2>Error 403</H2>\n</BODY>\n</HTML>\n')
20:15:55 web.1  | 172.17.0.1 - - [09/Jul/2017 20:15:55] "POST /alexa HTTP/1.1" 400 -

**Comment by audioeng** [comment]
Looks like you are getting a 403 forbidden from Google music APIs, sounds like you do not have the GOOGLE_EMAIL or GOOGLE_PASSWORD configured correctly. Please refer to the Setup section of the readme and the docker section to ensure you are setting those parameters correctly.

**Comment by ajdrausal** [comment]
I got this also in the debug logs 

DEBUG in music [/geemusic/geemusic/utils/music.py:58]:
20:08:27 web.1  | Done! Discovered 813 tracks.
20:08:27 web.1  | --------------------------------------------------------------------------------
20:08:35 web.1  | --------------------------------------------------------------------------------
20:08:35 web.1  | DEBUG in selection [/geemusic/geemusic/intents/selection.py:85]:
20:08:35 web.1  | Fetching song 21 pilots radio by None
20:08:35 web.1  | --------------------------------------------------------------------------------
20:08:35 web.1  | 172.17.0.1 - - [09/Jul/2017 20:08:35] "POST /alexa HTTP/1.1" 200 -
20:08:38 web.1  | 172.17.0.1 - - [09/Jul/2017 20:08:38] "GET /alexa/stream/Tjjbijcluqbz6swjita32xr7joi HTTP/1.1" 500 -

**Comment by stevenleeg** [comment]
@audioeng answer seems to be the most likely cause.

**Comment by ajdrausal** [comment]
@stevenleeg, The API was pulling discovered tracks, I would have been signed in at that point. However still got forbidden.
