### ISSUE TITLE
Server crashes after discovering tracks

### ISSUE THREAD

**Issue by chasx003** [stevenleeg/geemusic#110]
after starting foreman / Shows discovering tracks, server exits with code 247, and no real explanation. 

root@chazx:~/geemusic# foreman start
15:21:07 web.1  | started with pid 14507
15:21:08 web.1  | /usr/local/lib/python3.5/dist-packages/Cryptodome/Math/_Numbers_gmp.py:230: UserWarning: implicit cast to 'char *' from a different pointer type: will be forbidden in the future (check that the types are as you expect; use an explicit ffi.cast() if they are correct)
15:21:08 web.1  |   _gmp.gmp_snprintf(buf, c_size_t(buf_len), b("%Zd"), self._mpz_p)
15:21:08 web.1  |  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
15:21:08 web.1  |  * Restarting with stat
15:21:10 web.1  | /usr/local/lib/python3.5/dist-packages/Cryptodome/Math/_Numbers_gmp.py:230: UserWarning: implicit cast to 'char *' from a different pointer type: will be forbidden in the future (check that the types are as you expect; use an explicit ffi.cast() if they are correct)
15:21:10 web.1  |   _gmp.gmp_snprintf(buf, c_size_t(buf_len), b("%Zd"), self._mpz_p)
15:21:10 web.1  |  * Debugger is active!
15:21:10 web.1  |  * Debugger pin code: 106-350-210
15:21:21 web.1  | --------------------------------------------------------------------------------
15:21:21 web.1  | DEBUG in music [/root/geemusic/geemusic/utils/music.py:58]:
15:21:21 web.1  | Done! Discovered 16127 tracks.
15:21:21 web.1  | --------------------------------------------------------------------------------
15:21:23 web.1  | exited with code 247
15:21:23 system | sending SIGTERM to all processes

this is through a vps, so I've added a fake mac address to my .env file

**Comment by stevenleeg** [comment]
This hasn't seen any recent activity and will therefore be closed. Feel free to comment or file a new issue if you're still having trouble.
