### ISSUE TITLE
Issue Deploying via Heroku

### ISSUE THREAD

**Issue by newone757** [stevenleeg/geemusic#118]
I apologize if I'm out of line for requesting heroku support here but I am no coder/dev and google has gotten me nowhere. My instance seems to constantly crash and I haven't gotten it running yet after following the steps for heroku in the readme. 

Here is the log from heroku:

> 2017-08-08T02:36:05.553895+00:00 heroku[web.1]: Starting process with command `python3 server.py`
> 2017-08-08T02:36:08.557194+00:00 app[web.1]: Traceback (most recent call last):
> 2017-08-08T02:36:08.557213+00:00 app[web.1]:   File "server.py", line 1, in <module>
> 2017-08-08T02:36:08.557340+00:00 app[web.1]:     from geemusic import app
> 2017-08-08T02:36:08.557377+00:00 app[web.1]:   File "/app/geemusic/__init__.py", line 13, in <module>
> 2017-08-08T02:36:08.557482+00:00 app[web.1]:     if str(environ['DEBUG_MODE']) is True:
> 2017-08-08T02:36:08.557494+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/os.py", line 669, in __getitem__
> 2017-08-08T02:36:08.557770+00:00 app[web.1]:     raise KeyError(key) from None
> 2017-08-08T02:36:08.557775+00:00 app[web.1]: KeyError: 'DEBUG_MODE'
> 2017-08-08T02:36:08.685810+00:00 heroku[web.1]: Process exited with status 1
> 2017-08-08T02:36:08.696135+00:00 heroku[web.1]: State changed from starting to crashed

Sorry once again -- Hopefully, someone can point me in the right direction.

Thanks

**Comment by chamatht** [comment]
try this.
heroku config:set DEBUG_MODE=False

**Comment by newone757** [comment]
@chamatht you are a lifesaver! I figured it was something simple like that.

Finally got it all working after figuring out that it wouldn't stream audio because I already had 10 authorized devices on my Google Music Account. Deauthorized a couple and I'm up and running!. --hopefully that may help other who have issues with forbidden errors when trying to stream audio.
