### ISSUE TITLE
It works in German too

### ISSUE THREAD

**Issue by ehcg** [stevenleeg/geemusic#123]
Not really an issue, but my Alexa is in German and the skill worked. I followed the same instructions as for English_UK.

edit: I just to want to clarify, I speak to Alexa in Deunglish. "Alexa frag geemusic play some music". The German Alexa already understands some English, and I don't really listen to German music. When geemusic speaks back, it also does in Deunglish: numbers are German, everything else in English with a very strong German accent; it does not have the German accent with other skills speaking in English. 
PS. I have some playlists with Spanish names, so it is fun speaking Spanish with German and English in one sentence!

**Comment by koriwi** [comment]
i just translated the statements in the sourcecode to german, the Intent Schema and the custom slots and it works perfectly. took me like 90mins.

**Comment by cbruegg** [comment]
@koriwi Could you please upload your translation somewhere? Maybe just fork this repo? :)

**Comment by cbruegg** [comment]
I was too impatient 😄 [Here's my translation](https://gist.github.com/cbruegg/61d18f88a5cd873f0232c5403d37c506)

**Comment by Gerrett84** [comment]
It doesn´t work for me. If I say "Alexa frag gee music play some music" Alexa understand my words, but the skill won´t get started. Most time Alexa start some Amazon Unlimited music. I tried to change the invocation name but it doesn´t change anything. The skill is working fine on the Service Simulator. And sure, the skill is listed on my skills. I also tried the translated statements. Any idea ?

**Comment by pprotschka** [comment]
thanks for the german language file. when i try to add the intents in the german configuration i get:
**Error: There was a problem with your request: the slot type "AMAZON.MusicGroup"are not currently available for de_DE**

any ideas?

**Comment by pquerner** [comment]
@Gerrett84 did you fix that problem? I have the same issue now. See #190

**Comment by stevenleeg** [comment]
Since this is more of a comment than an issue I'm going to close this out. Let's move conversation over to #190 to discuss the issue @pquerner and @pprotschka are seeing (or open a separate issue).
