### ISSUE TITLE
Unsuccessful login - I do have 2 factor auth enabled?

### ISSUE THREAD

**Issue by ayoungh** [stevenleeg/geemusic#124]
Is it that because I do have 2 factor auth enabled my general username and password login details are not enough? if so what can I do?

**Comment by Danondso** [comment]
You're going to need to set up an app password, you can read more about
them here: https://support.google.com/accounts/answer/185833?hl=en

**Comment by Danondso** [comment]
Did that work for you?

**Comment by brianoc** [comment]
Can't speak for Ayoungh but I was having this exact problem and fixed everything for me.

Thanks! :)

**Comment by fergyfresh** [comment]
Mine didn't work until I did 2FA and app-password. Now that I have that figured out. When I use the test console on developer.amazon.com I get 200 reponses with the "Play some music" test, and it all appears to work fine, but won't play on my echo...

**Comment by hoangsong** [comment]
I set up an app password and I'm still failing to login.

This is what I get when I enter in foreman start

 started with pid 27855
06:03:19 web.1  | Traceback (most recent call last):
06:03:19 web.1  |   File "server.py", line 1, in <module>
06:03:19 web.1  |     from geemusic import app
06:03:19 web.1  |   File "/Users/hoang/geemusic/geemusic/__init__.py", line 20, in <module>
06:03:19 web.1  |     api = GMusicWrapper.generate_api(logger=app.logger)
06:03:19 web.1  |   File "/Users/hoang/geemusic/geemusic/utils/music.py", line 267, in generate_api
06:03:19 web.1  |     **kwargs)
06:03:19 web.1  |   File "/Users/hoang/geemusic/geemusic/utils/music.py", line 17, in __init__
06:03:19 web.1  |     raise Exception("Unsuccessful login. Aborting!")
06:03:19 web.1  | Exception: Unsuccessful login. Aborting!
06:03:19 web.1  | exited with code 1
06:03:19 system | sending SIGTERM to all processes

**Comment by stevenleeg** [comment]
This hasn't seen any recent activity and will therefore be closed. Feel free to comment or file a new issue if you're still having trouble.
