### ISSUE TITLE
 Unsuccessful login

### ISSUE THREAD

**Issue by emelnikov** [stevenleeg/geemusic#129]
I'm using geemusic in docker container. Less than week ago it stopped playing music and after container restart application crashes with 'Unsuccessful login. Aborting!'. Here is complete log:

> 12:29:35 web.1  | started with pid 7
> 12:29:41 web.1  | <object object at 0x7efcef35a1d0>
> 12:29:41 web.1  | Traceback (most recent call last):
> 12:29:41 web.1  |   File "server.py", line 1, in <module>
> 12:29:41 web.1  |     from geemusic import app
> 12:29:41 web.1  |   File "/geemusic/geemusic/__init__.py", line 22, in <module>
> 12:29:41 web.1  |     api = GMusicWrapper.generate_api(logger=app.logger)
> 12:29:41 web.1  |   File "/geemusic/geemusic/utils/music.py", line 266, in generate_api
> 12:29:41 web.1  |     **kwargs)
> 12:29:41 web.1  |   File "/geemusic/geemusic/utils/music.py", line 18, in __init__
> 12:29:41 web.1  |     raise Exception("Unsuccessful login. Aborting!")
> 12:29:41 web.1  | Exception: Unsuccessful login. Aborting!
> 12:29:41 web.1  | exited with code 1
> 12:29:41 system | sending SIGTERM to all processes

Since I did not make any changes to my droplet or docker container, I think there were some changes made by google which prevent the application from being connected.

**Comment by emelnikov** [comment]
Guys, does anyone has ideas why it could stop working? As far as I understand, I'm the only one here who is having such issue. I tried on another device (local VM) and got the same error. Also I added another google account to my family subscription and it does not login using its credentials as well. This tool worked so great and now I'm greatly upset.

**Comment by Danondso** [comment]
Did your app password expire?

**Comment by emelnikov** [comment]
Thanks! It was not exactly the case, because 2-factor authentication was not enabled for my account and I was using my google password. Enabling 2-factor auth and generation app password helped.
