### ISSUE TITLE
400 response errors in logs. Things appear to be working fine.

### ISSUE THREAD

**Issue by cooperaj** [stevenleeg/geemusic#135]
My logs are dotted with 

> 127.0.0.1 - - [23/Sep/2017 18:23:54] "POST /alexa HTTP/1.1" 400 -

Things however appear to be working just fine. I mostly get one of these after every song starts. The pattern seems to be. 

HEAD stream 200
GET stream 200
POST /alexa 400

I've got debug on but nothing additional is logged.

**Comment by SquareTheBase** [comment]
I saw this too.. it appears maybe the google stream service is returning 400s.  However, I wasn’t able to track down much info running this in the debugger.. will try again a bit later
