### ISSUE TITLE
Skill taking too long to respond

### ISSUE THREAD

**Issue by alexbaucom17** [stevenleeg/geemusic#14]
I am running into an issue where the skill is taking too long to respond and so it only works about 50% of the time. Unfortunately, there doesn't appear to be any way to increase the timeout value for alexa skills.

I am using a raspberry pi as my server and running ngrok and foreman as per the readme. I was thinking that the raspberry pi might be too slow but from watching the server when I give a request to alexa it appears that the request itself is taking quite a long time to even get to the pi.

Does anyone have tips on anything I could do on my end to fix this?

**Comment by huberf** [comment]
It is likely due to your network provider, and the latency inherent to a proxy. Others may know how to improve your current setup, but if all else fails, you can deploy a completely free Heroku instance which will definitely perform properly because the infrastructure runs on AWS. The steps to do this are detailed in the README.

**Comment by alexbaucom17** [comment]
Thanks for the tip. I looked into the Heroku free tier but I am worried about the fact that it will sleep after 30 minutes of inactivity. Do I have to be actively playing music through my echo and pinging the server with requests in order for it to stay active? Or will just having this code running in the background waiting for requests count as activity?

**Comment by stevenleeg** [comment]
yeah, I was wondering the same myself. it seems like heroku's free tier
might not be the best for this, as I wold think that the boot time would
cause some timeout issues.




On Tue, Jan 3, 2017, at 10:56 AM, Alex Baucom wrote:

> Thanks for the tip. I looked into the Heroku free tier but I am
> worried about the fact that it will sleep after 30 minutes of
> inactivity. Do I have to be actively playing music through my echo and
> pinging the server with requests in order for it to stay active? Or
> will just having this code running in the background waiting for
> requests count as activity?
> — You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub[1], or mute the
> thread[2].
> 




Links:

  1. https://github.com/stevenleeg/geemusic/issues/14#issuecomment-270146991

**Comment by stevenleeg** [comment]
to answer your original question: I would try to run this on your main computer with ngrok to see if you can get it running on a fully powered computer. if you're still having problems with that setup then it might be an issue with your ISP.

Has anyone else run into this issue before? I've yet to see it so it's hard for me to test/debug.

**Comment by huberf** [comment]
The Heroku sleep mode is definitely a potential issue, and with a quick test, it appears the boot time isn't usually fast enough. You might be able to use IFTTT or your local pi to query the server every 25 minutes or so, but if not you will definitely run into issues.

**Comment by stevenleeg** [comment]
We might want to add a note about that to the README. I can throw that up later today when I have time unless someone wants to submit a quick PR before then.

**Comment by alexbaucom17** [comment]
Okay I will try getting it up and running on another computer and see if that works. Any idea if I will need to generate a new google application password? I don't know if they are tied to specific hardware once used the first time

**Comment by huberf** [comment]
I have used the same password on multiple machines without issue.

**Comment by alexbaucom17** [comment]
Sounds great. I'll post an update with the results, hopefully by later today.

**Comment by alexbaucom17** [comment]
Alright I've got a quick update.

I ran through the setup to get my laptop running the server and it works perfectly. Quick responses every time and not a single "skill took too long" response. The laptop I have is a pretty cheap dual core that I use for basic coding stuff but it was still significantly faster than the raspberry pi, which was especially noticeable when doing the installation. My laptop took about 5 minutes and the raspberry pi takes about 20 minutes.

I had previously been using one of the original raspberry pi's but I got a model 3 for Christmas that is supposed to be quite a bit faster. I will try setting that one up as the server at some point and see if that works better.

**Comment by stevenleeg** [comment]
Glad to hear you got it up and running. Sucks that it isn't working on the original Pi but hopefully you'll have better luck with the 3rd gen chip.

I'm going to close this issue for now, but feel free to comment again letting us know if you have better luck!

**Comment by alexbaucom17** [comment]
So it appears that the original pi was the culprit here. I got my rpi 3 set up and it works just fine. I guess this software is more computationally demanding than I thought! Might be worth dropping a note about the original Pi not working into the readme. I could see a lot of people thinking the pi would be a perfect candidate for this sort of project.
