### ISSUE TITLE
Song recognition isn't great sometimes

### ISSUE THREAD

**Issue by jmahlman** [stevenleeg/geemusic#140]
Is there any way to make song name recognition better than it is now?  It seems to have trouble finding songs with roman numerals or words that sound like other words.

Example: Song I want; Key Entity Extraction IV by Coheed and Cambria
Geemusic hears: "Key entity extraction 4 by coheed and cambria" or if I say "I-V" it thinks I said "ivy" or "I V"
Another one: if I ask to play "M.I.A" the artist by saying "M I A" it never works.  

Amazon music does a much better job at finding songs...I know geemusic uses fuzzywuzzy to find the closest match..just didn't know if there was a better method..

**Comment by jmahlman** [comment]
I know it uses fuzzywuzzy to find the closest match..just didn't know if there was a better method.

**Comment by PostsDesert** [comment]
GeeMusic only uses fuzzywuzzy for playlist matching. The [song name] by [artist name] is directly handed from amazon to google play music.

**Comment by jmahlman** [comment]
Ah, okay.  Weird that it has a lot of trouble recognizing songs that work fine when I ask Amazon music to play them...

**Comment by PostsDesert** [comment]
Are you by any chance using the `non_us_custom_slot_version`?

**Comment by jmahlman** [comment]
I am not.  Maybe it's my Philly accent ;)
