### ISSUE TITLE
No music playing???

### ISSUE THREAD

**Issue by ChinookTx** [stevenleeg/geemusic#146]
Hi, I got my echo configured and everything works fine from the dev panel.  I can query my echo for playlists, and it recognises all my songs and playlists, but when I ask it to play something, it accepts the command but doesn't do anything...  I can even ask it what's playing and it will tell me, but nothing is playing!

What am I missing?

**Comment by jamaalscarlett** [comment]
see this: https://github.com/stevenleeg/geemusic/issues/102

**Comment by ChinookTx** [comment]
Yes, I had seen this, but everything appears to be configured properly...  My .env file contains:

> APP_URL=https://myhostname.ddns.net

My skill is configured with:

> https://myhostname.ddns.net/alexa

**Comment by ChinookTx** [comment]
After trying everything with self signed certs and not having any luck, I set it up as a proxy under nginx with proper certs and it's working fine.

**Comment by audioeng** [comment]
Yep, Alexa only talks to publicly trusted certs in my experience. It would
be great if they allowed you to upload a cert, especially for client
authentication

**Comment by jamaalscarlett** [comment]
I use ngrok to setup a secure tunnel to my local machine.

**Comment by PaulAnnekov** [comment]
@ChinookTx what trusted certificate do you use now? Let's Encrypt? And can you provide your nginx config, please?

**Comment by ChinookTx** [comment]
@PaulAnnekov I use a cert from PositiveSSL.

My nginx is really simple:


        listen 443 ssl;
        listen [::]:443 ssl;

        ssl_certificate /etc/ssl/certs/mycert-bundle;
        ssl_certificate_key /etc/ssl/private/mycert-private.pem;

        server_name www.mysite.ca;

        root /var/www/mysite.ca;
        index index.html;

        location / {
                try_files $uri $uri/ =404;
        }

        location /alexa {
                proxy_pass http://127.0.0.1:4000;
        }
