### ISSUE TITLE
Please support Japanese

### ISSUE THREAD

**Issue by sohsatoh** [stevenleeg/geemusic#150]
Amazon will release Echo in Japan.
Could you support Japanese?

**Comment by yamitzky** [comment]
Can I (or, we) contribute to support Japanese?
Now ASK seems to support it now, but I do not the limitation well.

https://developer.amazon.com/ja/blogs/alexa/post/0fcba76b-7460-4975-8fad-833996f6a23e/alexa-skills-kit-now-available-in-japan

**Comment by yamitzky** [comment]
I created https://github.com/stevenleeg/geemusic/pull/175, please help me to improve translation quality!

**Comment by fergyfresh** [comment]
@sohsatoh help @yamitzky improve translation quality. We have liftoff on Japanese so far though!
