### ISSUE TITLE
Server is not reachable via HTTPS

### ISSUE THREAD

**Issue by caltenhofen** [stevenleeg/geemusic#151]
Hi All!

I  followed all the instructions and basically everything seems to be working. But apparently the server does not accept HTTPS. When I access the URL with HTTP I get a "405 Method not allowed" error.
Maybe this is a silly question but do I have to specifically enable HTTPS anywhere? I have other webpages running on port 443 with HTTPS without any issues.
Any help is greatly appreciated!

Thanks,
Christian

**Comment by gricey** [comment]
Hi there, you'll need to somehow proxy the connection with SSL using a cert (either self-signed or one you own).  I use nginx and reverse proxy the connection using a cert from LetsEncrypt.

My config snippet is below (bear in mind the SSL part is elsewhere in the config...). I run the app in a docker container exposed on port 5000 and proxy through.

```
        location /alexa {

          proxy_set_header        Host $host;
          proxy_set_header        X-Real-IP $remote_addr;
          proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header        X-Forwarded-Proto $scheme;

          # docker is listening on exposed port 5000
          proxy_pass          http://localhost:5000;
          proxy_read_timeout  90;

          proxy_redirect      http://localhost:5000 https://yourdomain.com;
        }
```

**Comment by FireController1847** [comment]
Thanks @gricey, that fixed it for me!

**Comment by pquerner** [comment]
Same for Apache2.4+ VHost

```
ProxyPass / http://172.17.0.1:5000/
    ProxyPassReverse / http://172.17.0.1:5000/
    ProxyPreserveHost On
    RequestHeader set X-Forwarded-Proto "https" env=HTTPS
```

```172.17.0.1``` is the ip address of docker.

**Comment by lunyx** [comment]
Are there any more details on configuring this?  The readme just doesn't provide enough information.  I'm happy to research more on my own, but I would rather not spend a better part of the day attempting to figure out how to configure a webserver, loading in the env variables, getting it to start up automatically on server reboot, and serving the SSL certificate.

**Comment by pquerner** [comment]
@lunyx 
Thats a bit too much I think. In order to run this software one has to argue what requirements you need to be able to run it. To be able to handle a (web)server is one of the things I would say.

**Comment by lunyx** [comment]
@pquerner I suppose the question is the target audience for this software.  I presumed that it was for anyone with an Alexa that wants to use Google Music, not necessarily a developer.  I'll figure it out eventually, but it's certainly an unexpected roadblock after going through all the instructions.  If the intended audience is someone who understands how to set up a web server, we should probably specify that in the requirements.

**Comment by pquerner** [comment]
True, but you "normally" dont expect "normalos" to be searching github pages and expect its a double click on a file and it runs. ;) But yea, I go with you. There should be a "Requirements" header in the README file to make it clear that you have to bring this and that. 
Where "this" and "that" is of course to be defined.

**Comment by lunyx** [comment]
Sure, but you don't have to be searching github pages to get here.  It's the top result on Google for "Google Music Alexa".  Anyone with a VPS can follow along with these directions quite easily and find themselves stuck.

**Comment by stevenleeg** [comment]
I'd recommend skipping the webserver route and using [ngrok](https://ngrok.com/). It'll make your life a lot simpler and automatically set you up with SSL.

Perhaps this recommendation should be made more obvious in the README...

**Comment by lunyx** [comment]
Thanks for the suggestion.  However, with the pricing, I feel like heroku was the better option, which is what I ended up using for now.  I have some complications on my existing server that may actually even prevent me from doing the SSL setup (existing web server).

**Comment by audioeng** [comment]
I’ve been enjoying using haproxy on my pfSense router to provide SSL
offloading with LetsEncrypt automating the certs.

Nginx is also a great solution for providing SSL, I don’t know why anyone
would want to go through the hassle to front end SSL on anything else.

Not everyone is running a reverse proxy at their house mind you...

**Comment by stevenleeg** [comment]
@lunyx ngrok is free

**Comment by lunyx** [comment]
@stevenleeg The pricing page mentions HTTP/TCP tunnels on random URLs/ports for the free plan.  My understanding of that is that you are not guaranteed the same URL when you start the tunnel a second time (server reboot).

**Comment by stevenleeg** [comment]
Ah yeah, my solution to that was to simply leave the tunnel open indefinitely. It ended up working pretty reliably for me, even though it's certainly not the cleanest solution out there. Investing time into setting up a reverse proxy is certainly the cleaner way to go, but if you're looking to be lazy and just get this working for yourself ngrok seems to be a good solution.

**Comment by lunyx** [comment]
I'm still of the opinion that the documentation should be more clear that there is more to it than just `foreman start`.

**Comment by fergyfresh** [comment]
Submit a PR then if its unclear. I am unfamiliar with that option which is why i went the heroku free-tier route.

**Comment by lunyx** [comment]
@fergyfresh I submitted a PR for it.  I'm aware that most repos do not document how other tools work.  However, given that this is something that you can stumble upon even if you're not a developer, I think it's good to have a little more information on how to get started.

**Comment by dony71** [comment]
@gricey with your nginx config, what should I put in .env ?
APP_URL=https://myhost.com/alexa or APP_URL=https://myhost.com ??
also in amazon developer, https service endpoint type = https://myhost.com/alexa or https://myhost.com??
Somehow I got "There was a problem with the requested skill's response" when I test with alexa simulator
