### ISSUE TITLE
Unsuccessful login when deploying to heroku, works fine in Docker

### ISSUE THREAD

**Issue by ndtreviv** [stevenleeg/geemusic#154]
This issue was raised here: https://github.com/stevenleeg/geemusic/issues/57 as a comment, but as I believe it's different to the description on that issue, I'm raising a separate one in the hope that it gets more visibility.

I'm seeing this error in the logs:
```
2017-11-17T15:24:49.616927+00:00 heroku[web.1]: Starting process with command `python3 server.py`
2017-11-17T15:24:53.348190+00:00 app[web.1]: Traceback (most recent call last):
2017-11-17T15:24:53.348307+00:00 app[web.1]:   File "server.py", line 1, in <module>
2017-11-17T15:24:53.348570+00:00 app[web.1]:     from geemusic import app
2017-11-17T15:24:53.348614+00:00 app[web.1]:   File "/app/geemusic/__init__.py", line 20, in <module>
2017-11-17T15:24:53.348797+00:00 app[web.1]:     api = GMusicWrapper.generate_api(logger=app.logger)
2017-11-17T15:24:53.348854+00:00 app[web.1]:   File "/app/geemusic/utils/music.py", line 264, in generate_api
2017-11-17T15:24:53.349300+00:00 app[web.1]:     **kwargs)
2017-11-17T15:24:53.349303+00:00 app[web.1]:   File "/app/geemusic/utils/music.py", line 17, in __init__
2017-11-17T15:24:53.349476+00:00 app[web.1]:     raise Exception("Unsuccessful login. Aborting!")
2017-11-17T15:24:53.349479+00:00 app[web.1]: Exception: Unsuccessful login. Aborting!
2017-11-17T15:24:53.543155+00:00 heroku[web.1]: Process exited with status 1
2017-11-17T15:24:53.558296+00:00 heroku[web.1]: State changed from starting to crashed
```

The config is correct (email and password).
I've signed up to the free google play service.
I've run the docker container, and that works:
```
15:18:50 web.1  | started with pid 8
15:18:52 web.1  |  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
15:18:52 web.1  |  * Restarting with stat
15:18:52 web.1  | --------------------------------------------------------------------------------
15:18:52 web.1  | DEBUG in music [/geemusic/geemusic/utils/music.py:58]:
15:18:52 web.1  | Done! Discovered 0 tracks.
15:18:52 web.1  | --------------------------------------------------------------------------------
15:18:54 web.1  |  * Debugger is active!
15:18:54 web.1  |  * Debugger PIN: 151-322-483
15:18:54 web.1  | --------------------------------------------------------------------------------
15:18:54 web.1  | DEBUG in music [/geemusic/geemusic/utils/music.py:58]:
15:18:54 web.1  | Done! Discovered 0 tracks.
15:18:54 web.1  | --------------------------------------------------------------------------------
```

I've tried scaling back the app to 0 instances and then back up to 1 (effectively turning it off and on again), with no luck. 

It's weird that the docker container works, but this doesn't work on heroku. Any ideas?

**Comment by ndtreviv** [comment]
Initially I had a feeling this was a heroku error. I configured the GOOGLE_PASSWORD incorrectly at first, then I corrected it. When I looked at the app activity on heroku it didn't show me correcting it. So, I rolled back to just after deployment and reset the env vars again. This time they showed up in the activity, but I still get the Unsuccessful login error.

**Comment by ndtreviv** [comment]
Now I'm wondering if it's related to the android ID parameter being:  `Mobileclient.FROM_MAC_ADDRESS`

**Comment by ndtreviv** [comment]
If I run the gmusicapi Mobileclient login locally with the code, it fails to login.

**Comment by ndtreviv** [comment]
If I set the `ANDROID_ID` env var to random 16 hex chars, I get a message from Google about suspicious activity on my account and I'm forced to change my password.

**Comment by ndtreviv** [comment]
I've identified the ANDROID_ID that docker resolves, and have set that as an env var on Heroku - still no joy. For whatever reason, the gmusicapi won't authenticate me when deployed to docker.

**Comment by ndtreviv** [comment]
Why is this using the Mobileclient and not the webclient?

**Comment by ndtreviv** [comment]
I notice that the Webclient from gmusicapi doesn't require an android id, but is largely deprecated. Does authentication without android_id not work? Maybe I should take that up with them.

**Comment by ndtreviv** [comment]
Found this: https://github.com/simon-weber/gmusicapi/issues/584#issuecomment-343269657 which may be related.

**Comment by TheModdersDen** [comment]
Based on the above comment, you were or are in the same boat I was in. I enabled two-factor authentification, and then created an app password and used that as my GOOGLE_PASSWORD.

If you haven't created an app password, you can do so here (after you enable 2FA): https://myaccount.google.com/apppasswords

**Comment by ndtreviv** [comment]
This does work! Thanks!
