### ISSUE TITLE
Shuffle Song Support

### ISSUE THREAD

**Issue by PostsDesert** [stevenleeg/geemusic#16]
I have shuffle song support working on my branch. Is this something that would fit for Gee Music?

**Comment by stevenleeg** [comment]
Yup, that sounds awesome! Feel free to PR.

**Comment by OryanMo** [comment]
Is this pulled yet? @PostsDesert  @stevenleeg 
I can't seem to get it working..

**Comment by PostsDesert** [comment]
Yes, with a playlist playing say shuffle on.

**Comment by OryanMo** [comment]
That's great!
Thanks!
Are there other functions that were added and not documented?
And is there a way to play music without the "Ask gee music to"? @PostsDesert

**Comment by PostsDesert** [comment]
I honestly can't remember. If you look at this file it will show the sample utterances and therefore the commands. You can't get rid of the ask gee music to? but you can change it. I have mine set to ask music to because it's shorter.
