### ISSUE TITLE
Add command to play Thumbs up playlist

### ISSUE THREAD

**Issue by PaulAnnekov** [stevenleeg/geemusic#162]
As I can see you can get it by calling `Mobileclient.get_promoted_songs()` method.

**Comment by fergyfresh** [comment]
I started working on this last night because I want it. I'll push it to my fork later today and I can make a pull request if the general consensus is that we all want it.

**Comment by PaulAnnekov** [comment]
@fergyfresh why not? Do it.

**Comment by fergyfresh** [comment]
`GeeMusicThumbsUpPlayIntent` or `GeeMusicPlayThumbsUpIntent`? Do we want to logically group it in with the `Thumbs Up` stuff or with the `Play` stuff. I originally started it with former, but now I'm leaning towards the latter.

**Comment by PaulAnnekov** [comment]
@fergyfresh `GeeMusicPlayThumbsUpIntent` of course. Everything related to music playback is `GeeMusicPlay*`. `GeeMusicThumbs*` is for likes/dislikes.

**Comment by fergyfresh** [comment]
@PaulAnnekov dropped that PR and it works for me. Test it out if you want. You're going to need to update your `sampleUtterances.txt` and `intentSchema.json` as well as push my fork to your server.

**Comment by fergyfresh** [comment]
@stevenleeg close with PR #163

**Comment by fergyfresh** [comment]
@PaulAnnekov close this issue as it is fixed in #163 thanks.
