### ISSUE TITLE
Running from docker: KeyError

### ISSUE THREAD

**Issue by simonszu** [stevenleeg/geemusic#187]
I have created a docker container with the provided dockerfile. I have noticed that the container keeps restarting, so i looked in the log. The following lines rare repeated over and over again:
```
13:57:55 web.1  | started with pid 7
13:58:01 web.1  | Traceback (most recent call last):
13:58:01 web.1  |   File "server.py", line 1, in <module>
13:58:01 web.1  |     from geemusic import app
13:58:01 web.1  |   File "/geemusic/geemusic/__init__.py", line 20, in <module>
13:58:01 web.1  |     if str(environ['DEBUG_MODE']) is True:
13:58:01 web.1  |   File "/usr/lib/python3.6/os.py", line 669, in __getitem__
13:58:01 web.1  |     raise KeyError(key) from None
13:58:01 web.1  | KeyError: 'DEBUG_MODE'
13:58:02 web.1  | exited with code 1
13:58:02 system | sending SIGTERM to all processes
```
To be honest, i am quite new to all the docker stuff, and i am a little confused. I think this is more a code issue, than an administrative fault from my side, is this correct? So, i could use some help please.

**Comment by fergyfresh** [comment]
I think I have a fix for this. Be on the lookout for a PR.

**Comment by fergyfresh** [comment]
Try the code from PR #188.

**Comment by simonszu** [comment]
Yes, this PR fixed it. Thanks.
