### ISSUE TITLE
Make GeeMusic invocation more explicit

### ISSUE THREAD

**Issue by simonszu** [stevenleeg/geemusic#194]
Alexa tends to use Spotify/Prime as a fallback option when she hears a music related utterance Gee Music cannot handle. Since GeeMusic's language model isn't as perfectly as the buildin music service's model, she makes this fallback sometimes when you don't expect it, and plays music from spotify/prime. 

I would suggest a more explicit language model, like "Alexa, play music from <band> on Gee Music", also when Gee Music is already started, so you force her to explicitly use Gee Music, and also change her spoken feedback to "Here is some music from <band> on Gee Music", so you can explicitly determine if she is playing music from GeeMusic or Spotify/Prime. For developers, this creates an advantage of instant feedback if the utterance is recognized by GeeMusic or if one has to provide it yet.

**Comment by fergyfresh** [comment]
You can manually change the invocation when you set up your own skill. I personally don't really have a problem and would hate to say 12 words just to get to the part where I get to say what I want it to do.

Be more careful, LOL.
