### ISSUE TITLE
Getting 500 errors using Foreman on playing music with Artists

### ISSUE THREAD

**Issue by ashutoshmittal2309** [stevenleeg/geemusic#195]
I am seeing lot of 500 errors in logs when trying to search using Artists or Radio (using a free google music account which should at-least play radio's)

10:11:45 web.1  | Traceback (most recent call last):
10:11:45 web.1  |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1997, in __call__
10:11:45 web.1  |     return self.wsgi_app(environ, start_response)
10:11:45 web.1  |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1985, in wsgi_app
10:11:45 web.1  |     response = self.handle_exception(e)
10:11:45 web.1  |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1540, in handle_exception
10:11:45 web.1  |     reraise(exc_type, exc_value, tb)
10:11:45 web.1  |   File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
10:11:45 web.1  |     raise value
10:11:45 web.1  |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
10:11:45 web.1  |     response = self.full_dispatch_request()
10:11:45 web.1  |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
10:11:45 web.1  |     rv = self.handle_user_exception(e)
10:11:45 web.1  |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
10:11:45 web.1  |     reraise(exc_type, exc_value, tb)
10:11:45 web.1  |   File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
10:11:45 web.1  |     raise value
10:11:45 web.1  |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
10:11:45 web.1  |     rv = self.dispatch_request()
10:11:45 web.1  |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
10:11:45 web.1  |     return self.view_functions[rule.endpoint](**req.view_args)
10:11:45 web.1  |   File "/usr/local/lib/python3.6/site-packages/flask_ask/core.py", line 629, in _flask_view_func
10:11:45 web.1  |     result = self._map_intent_to_view_func(self.request.intent)()
10:11:45 web.1  |   File "/home/ec2-user/geemusic/geemusic/intents/selection.py", line 29, in play_artist
10:11:45 web.1  |     return statement(render_template("play_artist_none"))
10:11:45 web.1  |   File "/usr/local/lib/python3.6/site-packages/flask/templating.py", line 133, in render_template
10:11:45 web.1  |     return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
10:11:45 web.1  |   File "/usr/local/lib/python3.6/site-packages/jinja2/environment.py", line 869, in get_or_select_template
10:11:45 web.1  |     return self.get_template(template_name_or_list, parent, globals)
10:11:45 web.1  |   File "/usr/local/lib/python3.6/site-packages/jinja2/environment.py", line 830, in get_template
10:11:45 web.1  |     return self._load_template(name, self.make_globals(globals))
10:11:45 web.1  |   File "/usr/local/lib/python3.6/site-packages/jinja2/environment.py", line 804, in _load_template
10:11:45 web.1  |     template = self.loader.load(self, name, globals)
10:11:45 web.1  |   File "/usr/local/lib/python3.6/site-packages/jinja2/loaders.py", line 113, in load
10:11:45 web.1  |     source, filename, uptodate = self.get_source(environment, name)
10:11:45 web.1  | TypeError: 'TemplateNotFound' object is not iterable
10:11:45 web.1  | {
10:11:45 web.1  |   "context": {
10:11:45 web.1  |     "AudioPlayer": {
10:11:45 web.1  |       "playerActivity": "IDLE"
10:11:45 web.1  |     },
10:11:45 web.1  |     "System": {
10:11:45 web.1  |       "application": {
10:11:45 web.1  |         "applicationId": "amzn1.ask.skill.4045aea6-e792-417e-8fcf-4867ee855705"
10:11:45 web.1  |       },
10:11:45 web.1  |       "device": {
10:11:45 web.1  |         "supportedInterfaces": {}
10:11:45 web.1  |       },
10:11:45 web.1  |       "user": {
10:11:45 web.1  |         "userId": "amzn1.ask.account.AGPYRVCVTVKLKO4X2HOVTD33EV62D3MXHLIM4WXOSN7F6LVOK6GELXYSZIJP7FREUU4KIZOFUYSKBI6HFWM6CSROQACIVDFL76MEON4ICTXNMAQPKMBGUDHOKT6GER7KMEZ4MMQ4KA2NQTEFF5LUV3G2SEP27N72ULMC7GKRXFSVYPRJL7CQSWAODORIMXNM42S5W3DIDSD4UGA"
10:11:45 web.1  |       }
10:11:45 web.1  |     }
10:11:45 web.1  |   },
10:11:45 web.1  |   "request": {
10:11:45 web.1  |     "intent": {
10:11:45 web.1  |       "name": "GeeMusicPlayArtistIntent",
10:11:45 web.1  |       "slots": {
10:11:45 web.1  |         "artist_name": {
10:11:45 web.1  |           "name": "artist_name",
10:11:45 web.1  |           "value": "a tribe called quest"
10:11:45 web.1  |         }
10:11:45 web.1  |       }
10:11:45 web.1  |     },
10:11:45 web.1  |     "locale": "en-US",
10:11:45 web.1  |     "requestId": "EdwRequestId.2d98a37f-ad0f-4cf9-8a92-cac159e232cf",
10:11:45 web.1  |     "timestamp": "2018-03-04T10:11:45Z",
10:11:45 web.1  |     "type": "IntentRequest"
10:11:45 web.1  |   },
10:11:45 web.1  |   "session": {
10:11:45 web.1  |     "application": {
10:11:45 web.1  |       "applicationId": "amzn1.ask.skill.4045aea6-e792-417e-8fcf-4867ee855705"
10:11:45 web.1  |     },
10:11:45 web.1  |     "attributes": {},
10:11:45 web.1  |     "new": false,
10:11:45 web.1  |     "sessionId": "SessionId.372a9f64-f0cf-40bc-b7c0-610848d7df7a",
10:11:45 web.1  |     "user": {
10:11:45 web.1  |       "accessToken": null,
10:11:45 web.1  |       "userId": "amzn1.ask.account.AGPYRVCVTVKLKO4X2HOVTD33EV62D3MXHLIM4WXOSN7F6LVOK6GELXYSZIJP7FREUU4KIZOFUYSKBI6HFWM6CSROQACIVDFL76MEON4ICTXNMAQPKMBGUDHOKT6GER7KMEZ4MMQ4KA2NQTEFF5LUV3G2SEP27N72ULMC7GKRXFSVYPRJL7CQSWAODORIMXNM42S5W3DIDSD4UGA"
10:11:45 web.1  |     }
10:11:45 web.1  |   },
10:11:45 web.1  |   "version": "1.0"
10:11:45 web.1  | }
10:11:45 web.1  | {
10:11:45 web.1  |   "playerActivity": "IDLE"
10:11:45 web.1  | }
10:11:46 web.1  | 127.0.0.1 - - [04/Mar/2018 10:11:46] "POST /alexa HTTP/1.1" 500 -

Any help is appreciated as i am getting this error.

Sometimes i am getting in response on Alexa skill test screen. 

Start radio for artist Drake

Response-
{
  "version": "1.0",
  "response": {
    "outputSpeech": {
      "text": "Sorry, I couldn't find that artist.",
      "type": "PlainText"
    },
    "speechletResponse": {
      "outputSpeech": {
        "text": "Sorry, I couldn't find that artist."
      },
      "shouldEndSession": true
    }
  },
  "sessionAttributes": {}
}

I would try again after purchasing the subscription to confirm if these issues exists but till then if someone has faced similar issues and guide me it will be great.

**Comment by simonszu** [comment]
Your first error shows that you are trying to access a `GeeMusicPlayArtistIntent` which differs from `GeeMusicPlayArtistRadioIntent`. Are you sure that you explicitly started a radio? Just a plain Artist-playback isn't supported by free accounts, afair. 

What is the debuglog output of GeeMusic in situations where you get the Alexa response of the second error message?
