### ISSUE TITLE
Feature Request: List albums

### ISSUE THREAD

**Issue by alexbaucom17** [stevenleeg/geemusic#20]
I might be the only one who has this problem but I rarely remember album names anymore. But sometimes I still want to listen to a specific album but don't remember the name (but I know it when I hear it). It would be a nice feature if I could ask Alexa to list out the albums of a particular artist so I can figure out which one is the one I want to listen to.

If I find the time I might look into doing this myself but it would be a pretty steep learning curve for me as I am not super familiar with most of the packages this project uses.

**Comment by stevenleeg** [comment]
Yeee! This is an issue that I've had as well and I've been trying to think of a solution. Listing albums is hard because some artists just have *tons* of albums, and many times google music lists EPs/singles along with the albums. Lots of noise.

A couple of commands that I've thought would be useful:
```
Alexa, tell geemusic to play the latest album from LCD Soundsystem
Alexa, tell geemusic to play an album by artist Radiohead
Alexa, tell geemusic to play a different album
```

The last two commands would be randomly shuffling through albums, similar to the song shuffle that we're working on now.

**Comment by alexbaucom17** [comment]
Yes! Those commands would all be super useful.

You could also consider having two variations on listing (or something similar):
`Alexa, tell geemusic to list the latest albums by Radiohead`
`Alexa, tell geemusic to list all albums by Radiohead`

The first could just list a few (maybe 5 or so) and the second could just list all of them if that is what the user really wants. I would think that they would just say `Alexa, stop` once they hear the one they want and then tell her to play it. 

Idk if this is possible, but you could also consider checking how many songs are on the 'album' before listing it. If it is like 5 or less you could consider it an EP or single and not list it... but then again some people might want the EPs to be listed along with the albums...

**Comment by Danondso** [comment]
I have a super basic implementation of this right now running locally. Once I get it cleaned up and refined a little better I'll put a PR in.

**Comment by stevenleeg** [comment]
Awesome! I'm stoked to get this functionality in.

**Comment by Danondso** [comment]
'For' the play a different album command, should the list of played albums persist through each command  or should it only be made sure that the currently playing album doesn't get restarted?
