### ISSUE TITLE
There was a problem with the requested skill's response

### ISSUE THREAD

**Issue by funkho** [stevenleeg/geemusic#205]
I am having trouble with the Alexa skill set up.  I was able to pull the updated intent json from issue #200 , and the skill built without issues, but when I go to test, I am getting the generic error of "There was a problem with the requested skill's response".

When I type in for the test "tell gee music to play bombtrack by rage against the machine", here is the json response that I get.

```{
	"body": {
		"version": "1.0",
		"response": {
			"outputSpeech": {
				"type": "PlainText",
				"text": "Playing Bombtrack (Remastered) by Rage Against The Machine"
			},
			"card": {
				"type": "Standard",
				"title": "Playing Bombtrack (Remastered) by Rage Against The Machine",
				"text": "",
				"image": {
					"smallImageUrl": "https://lh3.googleusercontent.com/NH1urQ8uQib0BZ-P5K3s0NQA564DUKz0MQBcuzehMKtXFAFjoOqBwB8U3B89KaJqaVN70EtDnw",
					"largeImageUrl": "https://lh3.googleusercontent.com/NH1urQ8uQib0BZ-P5K3s0NQA564DUKz0MQBcuzehMKtXFAFjoOqBwB8U3B89KaJqaVN70EtDnw"
				}
			},
			"directives": [
				{
					"type": "AudioPlayer.Play",
					"playBehavior": "REPLACE_ALL",
					"audioItem": {
						"stream": {
							"token": "dce1d820-d74d-462c-b49a-03558a347d74",
							"url": "http://removed.ngrok.io/alexa/stream/Tu6lqnmlmvopwqakxk3p2xetqni",
							"offsetInMilliseconds": 0
						}
					}
				}
			],
			"shouldEndSession": true
		},
		"sessionAttributes": {}
	}
```

I have confirmed that the URL given in the 'audioitem' does play back the stream.  (I have removed the URL for this issue).

I thought that perhaps Amazon is requiring https for the response now?  I tested and https does work for the URL, but the error from Amazon is so generic that I'm just stabbing in the dark.  Any thoughts on what's going wrong here?

**Comment by funkho** [comment]
More debugging in the console shows that my original thought might be correct...

```
                            "type": "INVALID_RESPONSE",
                            "message": "The URL specified in the Play directive must be HTTPS"
```

**Comment by funkho** [comment]
I found that I had put the non-https URL into my .env file.  Fixing that has resolved my Alexa issue.

**Comment by lordfiSh** [comment]
still don't work for me... 
"There was a problem with the requested skill's response"

If I open the URL "https://removed.ngrok.io/alexa/stream/Tu6lqnmlmvopwqakxk3p2xetqni" it plays the steam just fine

**Comment by fergyfresh** [comment]
What is your APP_URL?

**Comment by fergyfresh** [comment]
It is because you don't have a valid CA that the Alexa can decrypt the message with. If you do it over http it should work, or try this fork https://github.com/fergyfresh/geemusic/tree/adds-test and set and additional environment variable `ASK_VERIFY_REQUESTS='False'`.

**Comment by lordfiSh** [comment]
thanks for the quick replay @fergyfresh but I did't save the Audio Player Option. Found it Problem in the Alexa  Dev Logs
