### ISSUE TITLE
Keep getting TypeError: Can't compile non template nodes

### ISSUE THREAD

**Issue by romashko** [stevenleeg/geemusic#206]
**Python version:** Python 3.5.2
**OS Version:** Ubuntu 16.04 LTS

I did everything by instructions, I'm running python in virtualenv, I use foreman and ngrok and keep getting TypeError: Can't compile non template nodes on every request.
I tried to google and looked at the source, but I still don't see the issue.
Is it a bug in the code or my setup issue?

`08:48:30 web.1  | 127.0.0.1 - - [08/Apr/2018 08:48:30] "POST /alexa HTTP/1.1" 500 -
08:48:30 web.1  | Traceback (most recent call last):
08:48:30 web.1  |   File "/home/test/alexa/geemusic/.venv/lib/python3.5/site-packages/flask/app.py", line 1997, in __call__
08:48:30 web.1  |     return self.wsgi_app(environ, start_response)
08:48:30 web.1  |   File "/home/test/alexa/geemusic/.venv/lib/python3.5/site-packages/flask/app.py", line 1985, in wsgi_app
08:48:30 web.1  |     response = self.handle_exception(e)
08:48:30 web.1  |   File "/home/test/alexa/geemusic/.venv/lib/python3.5/site-packages/flask/app.py", line 1540, in handle_exception
08:48:30 web.1  |     reraise(exc_type, exc_value, tb)
08:48:30 web.1  |   File "/home/test/alexa/geemusic/.venv/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
08:48:30 web.1  |     raise value
08:48:30 web.1  |   File "/home/test/alexa/geemusic/.venv/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
08:48:30 web.1  |     response = self.full_dispatch_request()
08:48:30 web.1  |   File "/home/test/alexa/geemusic/.venv/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
08:48:30 web.1  |     rv = self.handle_user_exception(e)
08:48:30 web.1  |   File "/home/test/alexa/geemusic/.venv/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
08:48:30 web.1  |     reraise(exc_type, exc_value, tb)
08:48:30 web.1  |   File "/home/test/alexa/geemusic/.venv/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
08:48:30 web.1  |     raise value
08:48:30 web.1  |   File "/home/test/alexa/geemusic/.venv/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
08:48:30 web.1  |     rv = self.dispatch_request()
08:48:30 web.1  |   File "/home/test/alexa/geemusic/.venv/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
08:48:30 web.1  |     return self.view_functions[rule.endpoint](**req.view_args)
08:48:30 web.1  |   File "/home/test/alexa/geemusic/.venv/lib/python3.5/site-packages/flask_ask/core.py", line 663, in _flask_view_func
08:48:30 web.1  |     result = self._launch_view_func()
08:48:30 web.1  |   File "/home/test/alexa/geemusic/geemusic/intents/selection.py", line 9, in login
08:48:30 web.1  |     text = render_template("login_text")
08:48:30 web.1  |   File "/home/test/alexa/geemusic/.venv/lib/python3.5/site-packages/flask/templating.py", line 133, in render_template
08:48:30 web.1  |     return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
08:48:30 web.1  |   File "/home/test/alexa/geemusic/.venv/lib/python3.5/site-packages/jinja2/environment.py", line 869, in get_or_select_template
08:48:30 web.1  |     return self.get_template(template_name_or_list, parent, globals)
08:48:30 web.1  |   File "/home/test/alexa/geemusic/.venv/lib/python3.5/site-packages/jinja2/environment.py", line 830, in get_template
08:48:30 web.1  |     return self._load_template(name, self.make_globals(globals))
08:48:30 web.1  |   File "/home/test/alexa/geemusic/.venv/lib/python3.5/site-packages/jinja2/environment.py", line 804, in _load_template
08:48:30 web.1  |     template = self.loader.load(self, name, globals)
08:48:30 web.1  |   File "/home/test/alexa/geemusic/.venv/lib/python3.5/site-packages/jinja2/loaders.py", line 125, in load
08:48:30 web.1  |     code = environment.compile(source, name, filename)
08:48:30 web.1  |   File "/home/test/alexa/geemusic/.venv/lib/python3.5/site-packages/jinja2/environment.py", line 581, in compile
08:48:30 web.1  |     defer_init=defer_init)
08:48:30 web.1  |   File "/home/test/alexa/geemusic/.venv/lib/python3.5/site-packages/jinja2/environment.py", line 543, in _generate
08:48:30 web.1  |     optimized=self.optimized)
08:48:30 web.1  |   File "/home/test/alexa/geemusic/.venv/lib/python3.5/site-packages/jinja2/compiler.py", line 78, in generate
08:48:30 web.1  |     raise TypeError('Can\'t compile non template nodes')
08:48:30 web.1  | TypeError: Can't compile non template nodes
`

**Comment by romashko** [comment]
Upgraded to python 3.6.2 with pyenv, getting the same issue. May it be the encoding issue or file reading issue? Any ideas how to fix it?
Thanks.

**Comment by romashko** [comment]
It works on my OS X workstation but doesn't work on Ubuntu server! I don't know what to do with it, I just can't run this on my workstation all the time.

**Comment by fergyfresh** [comment]
I'll try to get this working on an Ubuntu 16.04 server tonight. It works on my computer and I run Ubuntu 14.04 so ill upgrade to 160.04 and try to figure it out. That error is 100% from the `jinja2` `render_template`.

**Comment by romashko** [comment]
Totally weird. It just started working after one of the restart of foreman. I changed nothing, just stopped foreman and started it again. Oh.

**Comment by fergyfresh** [comment]
Yeah. Works for me too.

**Comment by fergyfresh** [comment]
@stevenleeg close this one too.

**Comment by cjmasini** [comment]
I am also getting this error and am unsure how I can go about fixing it. I am also running in virtualenv using foreman and ngrok. The only potential cause I can think of is that I modified __init__.py. I removed the path=TEMPLATE_DIR from the following line:
`ask = Ask(app, '/alexa')#, path=TEMPLATE_DIR)`
since leaving it in resulted in the following error: UnicodeDecodeError: 'ascii codec can't decode byte 0xc2 in position 937: ordinal not in range(128)'
Any ideas or tips?

**Comment by fergyfresh** [comment]
Restart foreman like @romashko said worked for him.

**Comment by cjmasini** [comment]
If by restarting foreman you mean stopping it and running foreman start again I tried that. If their is some other foreman command I should be running to restart I'll try that but I couldn't find anything via a google search. The stack trace for the ascii error is below:
`19:43:15 web.1  | started with pid 19727
19:43:17 web.1  | Traceback (most recent call last):
19:43:17 web.1  |   File "server.py", line 1, in <module>
19:43:17 web.1  |     from geemusic import app
19:43:17 web.1  |   File "/home/masinico/geemusic/geemusic/__init__.py", line 14, in <module>
19:43:17 web.1  |     ask = Ask(app, '/alexa', path=TEMPLATE_DIR)
19:43:17 web.1  |   File "/home/masinico/geemusic/.venv/lib/python3.5/site-packages/flask_ask/core.py", line 93, in __init__
19:43:17 web.1  |     self.init_app(app, path)
19:43:17 web.1  |   File "/home/masinico/geemusic/.venv/lib/python3.5/site-packages/flask_ask/core.py", line 140, in init_app
19:43:17 web.1  |     app.jinja_loader = ChoiceLoader([app.jinja_loader, YamlLoader(app, path)])
19:43:17 web.1  |   File "/home/masinico/geemusic/.venv/lib/python3.5/site-packages/flask_ask/core.py", line 858, in __init__
19:43:17 web.1  |     self._reload_mapping()
19:43:17 web.1  |   File "/home/masinico/geemusic/.venv/lib/python3.5/site-packages/flask_ask/core.py", line 864, in _reload_mapping
19:43:17 web.1  |     self.mapping = yaml.safe_load(f.read())
19:43:17 web.1  |   File "/home/masinico/geemusic/.venv/lib/python3.5/encodings/ascii.py", line 26, in decode
19:43:17 web.1  |     return codecs.ascii_decode(input, self.errors)[0]
19:43:17 web.1  | UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 937: ordinal not in range(128)'
The stack trace for the type error is identical to romashko posted above.

**Comment by fergyfresh** [comment]
What version of python are you using?

**Comment by fergyfresh** [comment]
Do you have a non-Unicode `LANGUAGE` environment variable.

**Comment by cjmasini** [comment]
I was using 3.5 but upgrading to 3.6 didn't fix the issue. The LANGUAGE environment variable doesn't exist on my system but I've tried eliminating that part of the code and hard-coding the language information, which also failed to change anything. I've gotten this working on my regular laptop too, it just doesn't want to run on the old laptop I use as a server.

**Comment by fergyfresh** [comment]
Must be some issue on your end then. Sit packages issue I presume.
