### ISSUE TITLE
Why no wiki?

### ISSUE THREAD

**Issue by lmatter** [stevenleeg/geemusic#207]
Hi, I just got this working and I love it!!.  I am running it on my raspberry pi 3 b+ and it's works (nearly) flawlessly.  Along the way to getting it working I learned a lot about AWS Alexa skills, the ASK CLI and API, and a great number of ngrok-like HTTPS front ends that cost nothing, some better than others.

I would like to document my Journey for others.  My goal is to completely automate the installation via the CLI such that changes to the GUI don't cause issues in the future.  

Should I just write it up and submit a pull request?  Thanks.

**Comment by stevenleeg** [comment]
Hmm yeah, I'm happy to open up the wiki to some additional documentation that may not be suitable for the README (or could allow us to organize things a bit better). I'll go ahead and do that now.
