### ISSUE TITLE
Unable to install Foreman due to no write permission.

### ISSUE THREAD

**Issue by smithduluth** [stevenleeg/geemusic#209]
When I try to run "gem install foreman", I get "Gem:file PermissionsError"
"you don't have write permission for the /var/lib/gems/2.3.0 directory"

I am running latest Raspian on a RPI 3 with Python 3.5

I have tried changing permissions to all, but it was not allowed.

**Comment by stevenleeg** [comment]
You likely need to run the command with `sudo`. This is unrelated to geemusic so I'm going to close this issue.
