### ISSUE TITLE
Make the playlist/album restart from the beginning

### ISSUE THREAD

**Issue by PostsDesert** [stevenleeg/geemusic#21]
It would be nice if a playlist/album would restart from the beginning like it does in GPM. I would be happy to make a PR if this is something that would work.

**Comment by PostsDesert** [comment]
I have It working {on my fork here.](https://github.com/PostsDesert/geemusic/commit/a4facb0aded80a0e2a0fb0d0dc0498047e7310f8)

**Comment by stevenleeg** [comment]
I don't quite get what this feature would be. What do you mean restart from the beginning/what exactly would trigger this restart?

**Comment by PostsDesert** [comment]
So on Google Music when you reach say song 40 and go to the next song it brings you to song 1

**Comment by PostsDesert** [comment]
The loop support function also depends on this fluid queue reset too. Should I make a PR so you can look at it?

**Comment by stevenleeg** [comment]
I'm going to close this issue and continue the discussion in #27.
