### ISSUE TITLE
Not returning songs or artists

### ISSUE THREAD

**Issue by iamfuzz** [stevenleeg/geemusic#211]
I set this up on Heroku and Playlist functionality works, and Herokus logs show that geemusic successfully discovered all of my songs.

However, when I try to play a song, or artist, gee music doesn't find it.

{
	"body": {
		"version": "1.0",
		"response": {
			"outputSpeech": {
				"type": "PlainText",
				"text": "Sorry, I couldn't find that song."
			},
			"shouldEndSession": true
		},
		"sessionAttributes": {}
	}
}

**Comment by fergyfresh** [comment]
Few questions for ya @iamfuzz. Do you pay for Google Play Music subscription? Are you trying to play songs from your personal library and not from Google Play Music?

**Comment by iamfuzz** [comment]
Oh, that's a bummer.  I didn't realize it couldn't play songs from your library. (No, I don't pay for any subscription)  I might take a crack at it.

**Comment by fergyfresh** [comment]
You CAN play songs from your library. You just can't individual songs. I can write something tonight for you to try out. I don't have any free music, but it doesn't mean we can't get it working for you.

**Comment by iamfuzz** [comment]
That'd be awesome if you find the time.  Otherwise, I'll take a crack at it at some point myself.

**Comment by fergyfresh** [comment]
Closing in favor of #145.
