### ISSUE TITLE
Lots of 400 BAD REQUEST errors

### ISSUE THREAD

**Issue by loseirdo** [stevenleeg/geemusic#212]
I'm having an issue with the Gee Music skill (running Foreman) where I get lots of 400 errors in a row when playing songs from a playlist. Oftentimes, the request will eventually go through, and the next song will play with only some minor latency, but eventually, the server will throw up a bunch of 400 errors and then simply stop.

From ngrok:

> {
    "version": "1.0",
    "context": {
        "AudioPlayer": {
            "offsetInMilliseconds": 220000,
            "token": "abf2dcd0-21ef-44c1-afb3-d5a6aa9e4c98",
            "playerActivity": "FINISHED"
        },
        "System": {
            "application": {
                "applicationId": "amzn1.ask.skill.07946154-85b1-404d-a979-1374a7274b42"
            },
            "user": {
                "userId": "amzn1.ask.account.AH2LXKTFCFBHLUVB5HOQKWJS3AOC32VBRFLXTWLXXXKU6HSW4STM4PEJAM7GRB5OUGNOPAAZOZEB2O4PH4B4O6CJFCJI7TZZIGUJ3EYEO6D7T5TT2TX6AFN3TDWKNPOCI2K2PWUX5A2FBKWQA22FV4XEB3S4XEQTYW34BGHYVSW2P2SFVVDU4EFRAJLME6H2EOVURL5NA7MGLPQ"
            },
            "device": {
                "deviceId": "amzn1.ask.device.AG5OGZYLKPYKWYEZKAXG6VVYYHSGQNZ5PEM34VEILN43HVZETMPUDKIGIW3A52H4KMDSV7AOPQ5PFJMJCAPWPJI2DIGL2B26KJ3WM645KIAOLJWOTZNY6UTUROJ3ODNP4MPGSNNRWQFTCVKSUD3IFAXGGHMZVLMAGE6E5E4QZZUG26TACTYXO",
                "supportedInterfaces": {
                    "AudioPlayer": {}
                }
            },
            "apiEndpoint": "https://api.amazonalexa.com",
            "apiAccessToken": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IjEifQ.eyJhdWQiOiJodHRwczovL2FwaS5hbWF6b25hbGV4YS5jb20iLCJpc3MiOiJBbGV4YVNraWxsS2l0Iiwic3ViIjoiYW16bjEuYXNrLnNraWxsLjA3OTQ2MTU0LTg1YjEtNDA0ZC1hOTc5LTEzNzRhNzI3NGI0MiIsImV4cCI6MTUyNTM2MTgzMiwiaWF0IjoxNTI1MzU4MjMyLCJuYmYiOjE1MjUzNTgyMzIsInByaXZhdGVDbGFpbXMiOnsiY29uc2VudFRva2VuIjpudWxsLCJkZXZpY2VJZCI6ImFtem4xLmFzay5kZXZpY2UuQUc1T0daWUxLUFlLV1lFWktBWEc2VlZZWUhTR1FOWjVQRU0zNFZFSUxONDNIVlpFVE1QVURLSUdJVzNBNTJINEtNRFNWN0FPUFE1UEZKTUpDQVBXUEpJMkRJR0wyQjI2S0ozV002NDVLSUFPTEpXT1RaTlk2VVRVUk9KM09ETlA0TVBHU05OUldRRlRDVktTVUQzSUZBWEdHSE1aVkxNQUdFNkU1RTRRWlpVRzI2VEFDVFlYTyIsInVzZXJJZCI6ImFtem4xLmFzay5hY2NvdW50LkFIMkxYS1RGQ0ZCSExVVkI1SE9RS1dKUzNBT0MzMlZCUkZMWFRXTFhYWEtVNkhTVzRTVE00UEVKQU03R1JCNU9VR05PUEFBWk9aRUIyTzRQSDRCNE82Q0pGQ0pJN1RaWklHVUozRVlFTzZEN1Q1VFQyVFg2QUZOM1REV0tOUE9DSTJLMlBXVVg1QTJGQktXUUEyMkZWNFhFQjNTNFhFUVRZVzM0QkdIWVZTVzJQMlNGVlZEVTRFRlJBSkxNRTZIMkVPVlVSTDVOQTdNR0xQUSJ9fQ.CjfQeW7-w9JJdU1bxjRESdr6CbK3o28lVHCEVWCSqItva18RgPBGJ136tOElPlBohZ3v8-ForxiHWsAp_fYiSvE4-jR8UC_5t5L1hLXN0RZqyGvMaq2kEDmQk5QZ9ntDUkJiQu_zGQ9ZCMfhayRCs4zlQg_POEc8ZHcdMljBZCGtSGKN1YNe11hFzHcYcwroj8haNdQQsTPePeuUYqkxQAQo0rQI9lP1kueMfgbh6mbPfvCnefTZe1o8e6KVe7jFA_tJP0dah2U5i3MggV9mBESfLeesgieEXoRJc4cXGMDVUmzXR4q70XMj9A_fgmoBsPvkpUikVTF-nt-MNNC0cg"
        }
    },
    "request": {
        "type": "System.ExceptionEncountered",
        "requestId": "amzn1.echo-api.request.91a08e90-4f1c-4a18-aaa3-f53aab160970",
        "timestamp": "2018-05-03T14:37:13Z",
        "locale": "en-US",
        "error": {
            "type": "INVALID_RESPONSE",
            "message": "An exception occurred while dispatching the request to the skill."
        },
        "cause": {
            "requestId": "amzn1.echo-api.request.21dd8e5b-6fe9-409a-820c-7dab1c6f768e"
        }
    }
}

Restarting the server will get it working again, but it gradually (over the course of an hour or so) starts generating more and more 400 errors until it simply stops trying. That pretty much limits me to one playlist per server session. Does anybody have any idea what might be causing this? I'm using a free Google Play account, so I'm only able to test this with playlists right now. Any thoughts would be appreciated.

**Comment by fergyfresh** [comment]
Are you using an app specific password? I have seen this similar thing happen when I wasn't using that.

**Comment by loseirdo** [comment]
Yes, I am. I'm really at a loss for what the culprit might be.

**Comment by fergyfresh** [comment]
The Free Music stuff has always been on the fritz, maybe peruse through some of those issues and try to work with someone on their workarounds if they have any.

**Comment by loseirdo** [comment]
I'll take a look. Thanks.

**Comment by fergyfresh** [comment]
Closing in favor of #145.
