### ISSUE TITLE
Run on Windows

### ISSUE THREAD

**Issue by parabola949** [stevenleeg/geemusic#216]
Not an issue actually, just wanted to give a heads up, I got this running on Windows.  Took a bit of messing with, because Windows doesn't let you really do reverse proxy that well.  I moved it to port 5000 because my machine yelled at me for trying to use 4000, then wrote a small web app that takes in the traffic on 443 / 80 and forwards the request to port 5000, then spits back the response.

Basic instructions:
Deploy the web app to IIS, run the python app.  They should start talking to each other.

https://github.com/parabola949/geemusic/commit/cf80ad17d5482ce9a85b4fade70d538424fc0fd2

I'm NOT submitting this as a PR because it's not an improvement, more like a port to make it run elsewhere.

As for HTTPS, I went the lazy route and used CloudFlare...

**Comment by fergyfresh** [comment]
You couldn't use ngrok to do expose your localhost? I thought ngrok worked cross platform, I have no idea as I do all my dev in Linux environments. I just thought it was cross platform ootb.

**Comment by parabola949** [comment]
Possibly.  Never tried using it on Windows, because... well, windows sucks.  Let's face it.

**Comment by fergyfresh** [comment]
Just an idea. I used Windows Subsystem for Linux with ngrok and it just worked as is.
