### ISSUE TITLE
silence while playing

### ISSUE THREAD

**Issue by Bronskiy** [stevenleeg/geemusic#232]
Looks like all works fine but there is no sound.
It worked before but a couple of weeks ago it is stopped to play music.
I decided to update skill because there were many new changes but it hasn't fixed my problem.
Even if I ask 'What is currently playing?' it says correct answer and I can see all commands with Alexa App in the iphone app.

**Comment by fergyfresh** [comment]
What deployment scheme did you use? Did you check for error logs?

**Comment by Bronskiy** [comment]
I'm using a Heroku instance. There are no errors in heroku or skill logs.
![2018-06-15_12-23-55](https://user-images.githubusercontent.com/1948199/41466005-418b9320-7098-11e8-945b-e1711989560d.png)
![2018-06-15_12-29-54](https://user-images.githubusercontent.com/1948199/41466009-431fd26e-7098-11e8-97ed-cd4e3119b1e8.png)

**Comment by fergyfresh** [comment]
Doesn't play music from the test took online

**Comment by Bronskiy** [comment]
it doesn't play any music from the device. I provided these screenshots to show that there are no visible errors. The same commands I'm using by voice and the only sound is alexa's voice response

**Comment by fergyfresh** [comment]
Honestly, this is not an issue that I've ever seen. The only time I played music and heard silence was when I messed up integrating  AWS lambda and it was spouting and error message out at me.

**Comment by Bronskiy** [comment]
I think there is an issue because of recently updated amazon skill service

**Comment by Bronskiy** [comment]
it is just stopped to play sounds just suddenly without any interaction to code

**Comment by fergyfresh** [comment]
Try to look if your server is running

**Comment by fergyfresh** [comment]
At the very least it should say there was a problem with the requested
skills response.

**Comment by Bronskiy** [comment]
found my problem https://github.com/stevenleeg/geemusic/issues/220

**Comment by Bronskiy** [comment]
this is duplicated problem and it could be closed
