### ISSUE TITLE
"There Was a Problem With the Requested Skills Response"

### ISSUE THREAD

**Issue by gitAuss1e** [stevenleeg/geemusic#239]
Hey,

Pretty much what the title says. I can say "Alexa, open Gee Music" and it will give me the little welcome message but when I try to do anything else I get "There was a problem with the requested skills response". What do I need to provide to get assistance?

Thanks!

**Comment by jagauthier** [comment]
@gitAuss1e I am having this issue as well.  The server is throwing an exception:

20:11:34 web.1  | 192.210.206.47 - - [24/Jul/2018 20:11:34] "POST /alexa HTTP/1.1" 500 -
20:11:35 web.1  | Traceback (most recent call last):
20:11:35 web.1  |   File "/home/geemusic/geemusic/.venv/lib/python3.5/site-packages/flask/app.py", line 1997, in __call__
20:11:35 web.1  |     return self.wsgi_app(environ, start_response)
20:11:35 web.1  |   File "/home/geemusic/geemusic/.venv/lib/python3.5/site-packages/flask/app.py", line 1985, in wsgi_app
20:11:35 web.1  |     response = self.handle_exception(e)
20:11:35 web.1  |   File "/home/geemusic/geemusic/.venv/lib/python3.5/site-packages/flask/app.py", line 1540, in handle_exception
20:11:35 web.1  |     reraise(exc_type, exc_value, tb)
20:11:35 web.1  |   File "/home/geemusic/geemusic/.venv/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
20:11:35 web.1  |     raise value
20:11:35 web.1  |   File "/home/geemusic/geemusic/.venv/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
20:11:35 web.1  |     response = self.full_dispatch_request()
20:11:35 web.1  |   File "/home/geemusic/geemusic/.venv/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
20:11:35 web.1  |     rv = self.handle_user_exception(e)
20:11:35 web.1  |   File "/home/geemusic/geemusic/.venv/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
20:11:35 web.1  |     reraise(exc_type, exc_value, tb)
20:11:35 web.1  |   File "/home/geemusic/geemusic/.venv/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
20:11:35 web.1  |     raise value
20:11:35 web.1  |   File "/home/geemusic/geemusic/.venv/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
20:11:35 web.1  |     rv = self.dispatch_request()
20:11:35 web.1  |   File "/home/geemusic/geemusic/.venv/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
20:11:35 web.1  |     return self.view_functions[rule.endpoint](**req.view_args)
20:11:35 web.1  |   File "/home/geemusic/geemusic/.venv/lib/python3.5/site-packages/flask_ask/core.py", line 767, in _flask_view_func
20:11:35 web.1  |     result = self._map_intent_to_view_func(self.request.intent)()
20:11:35 web.1  |   File "/home/geemusic/geemusic/geemusic/intents/selection.py", line 29, in play_artist
20:11:35 web.1  |     return statement(render_template("play_artist_none"))
20:11:35 web.1  |   File "/home/geemusic/geemusic/.venv/lib/python3.5/site-packages/flask/templating.py", line 133, in render_template
20:11:35 web.1  |     return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
20:11:35 web.1  |   File "/home/geemusic/geemusic/.venv/lib/python3.5/site-packages/jinja2/environment.py", line 869, in get_or_select_template
20:11:35 web.1  |     return self.get_template(template_name_or_list, parent, globals)
20:11:35 web.1  |   File "/home/geemusic/geemusic/.venv/lib/python3.5/site-packages/jinja2/environment.py", line 830, in get_template
20:11:35 web.1  |     return self._load_template(name, self.make_globals(globals))
20:11:35 web.1  |   File "/home/geemusic/geemusic/.venv/lib/python3.5/site-packages/jinja2/environment.py", line 804, in _load_template
20:11:35 web.1  |     template = self.loader.load(self, name, globals)
20:11:35 web.1  |   File "/home/geemusic/geemusic/.venv/lib/python3.5/site-packages/jinja2/loaders.py", line 113, in load
20:11:35 web.1  |     source, filename, uptodate = self.get_source(environment, name)
20:11:35 web.1  |   File "/home/geemusic/geemusic/.venv/lib/python3.5/site-packages/flask/templating.py", line 57, in get_source
20:11:35 web.1  |     return self._get_source_fast(environment, template)
20:11:35 web.1  |   File "/home/geemusic/geemusic/.venv/lib/python3.5/site-packages/flask/templating.py", line 85, in _get_source_fast
20:11:35 web.1  |     raise TemplateNotFound(template)
20:11:35 web.1  | jinja2.exceptions.TemplateNotFound: play_artist_none

I'm not sure it's talking to Google Music correctly either.
When I try something like "ask gee music list all albums by pink floyd"

20:12:26 web.1  | {"playerActivity": "IDLE"}
20:12:27 web.1  | {"response": {"outputSpeech": {"text": "Unable to find the artist you requested.", "type": "PlainText"}, "shouldEndSession": true}, "sessionAttributes": {}, "version": "1.0"}
20:12:27 web.1  | 192.210.206.47 - - [24/Jul/2018 20:12:27] "POST /alexa HTTP/1.1" 200 -

But the JSON does contain the correct data.
"request": {
		"type": "IntentRequest",
		"timestamp": "2018-07-25T00:13:21Z",
		"locale": "en-US",
		"intent": {
			"name": "GeeMusicListAllAlbumsIntent",
			"confirmationStatus": "NONE",
			"slots": {
				"artist_name": {
					"name": "artist_name",
					"value": "pink Floyd",
					"confirmationStatus": "NONE"
				}
			}
		}
	}

**Comment by jagauthier** [comment]
The free version of Google Music.  Yes, I am attempting to listen to my own library.

**Comment by fergyfresh** [comment]
gonna close this in favor of #145.

**Comment by jagauthier** [comment]
oh, gotcha! So this requires a subscription at the moment.

**Comment by fergyfresh** [comment]
Yeah, there was an attempt by someone to make it work with the free music feature, but I don't know the current status and we really need someone that is familiar with using the `gmusicapi` to stream their library and add in the ability to stream free music as well.
