### ISSUE TITLE
Any plans to support YouTube Music?

### ISSUE THREAD

**Issue by SacredSkull** [stevenleeg/geemusic#243]
There are rumors that YouTube Music will be replacing Google Music at some point. Are there any plans to support this inside this skill? On the gmusicapi repo [an issue exists for this](https://github.com/simon-weber/gmusicapi/issues/609), but they feel like it might be a job for a completely new library. Though, given that there are suggestions that they are not meant to exist side-by-side, i.e. YT should replace GMusic, I think that it probably could fall under it's jurisdiction.

On the other hand, the [Google Music Desktop Player](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-) already has beta support for YT Music (I've been using it for several weeks - it's actually very good with few bugs), so it can be accomplished.

**Comment by fergyfresh** [comment]
If they rebrand, maybe. I doubt they would entirely deprecate their API, which the unofficial gmusicapi leverages heavily. And as you said this is really very easy on our end as there are classes propped up wrapping the gmusicapi, so if it changes, it would be as simple as creating another class.
