### ISSUE TITLE
Can't get information about a track with no album art

### ISSUE THREAD

**Issue by mikeage** [stevenleeg/geemusic#244]
As it says in the title; if you ask for information about the current track (`alexa, ask gee music what the current song is`), and there's no thumbnail, it fails. 

This patch fixes it, but i'm not sure if there's a better URL to use, which is why I'm not submitting a PR at this point.

```patch
commit 34d9c0d48626e250353b8ce410689c02fabbc7ee (HEAD -> master, heroku/no_albumart, heroku/master, no_albumart)
Author: Mike Miller <github@mikeage.net>
Date:   Sat Sep 29 22:30:24 2018 +0300

    Support 'what is this song' where there's no album art

diff --git a/geemusic/intents/playback.py b/geemusic/intents/playback.py
index c86e650..8317271 100644
--- a/geemusic/intents/playback.py
+++ b/geemusic/intents/playback.py
@@ -147,7 +147,10 @@ def currently_playing():
     if track is None:
         return audio(render_template("currently_playing_none"))

-    thumbnail = api.get_thumbnail(queue.current_track()['albumArtRef'][0]['url'])
+    try:
+        thumbnail = api.get_thumbnail(queue.current_track()['albumArtRef'][0]['url'])
+    except KeyError:
+        thumbnail = "http://invalid"
     return statement(render_template("success_title")\
                            + render_template("success_text",
                                              song=track['title'],
```

**Comment by fergyfresh** [comment]
I mean. I don't know of anyone that uses this on anything besides an Echo/Dot so I don't know HOW entirely important the picture is. Does it crash on the `['albumArtRef']` not being there though?

I would accept a patch for this as long as you changed two things.
- Check for the field that's causing it to crash in an if statement instead of a `try`/`except`.
- Try to use `thumbnail = None`

Like:
```
if queue.current_track().has_key('albumArtRef')
    thumbnail = api.get_thumbnail(queue.current_track()['albumArtRef'][0]['url'])
else:
    thumbnail = None
```

**Comment by mikeage** [comment]
Yes, it throws a `KeyError`. I personally prefer EAFP rather than LBYL for stuff like this, but style is personal :-)

One other suggestion; it's better to use `albumArtRef in queue.current_track()` rather than `has_key()`; Python 3 removes the `has_key()` completely.

I'll submit a patch

**Comment by fergyfresh** [comment]
You can EAFP if you want here just explicitly use the KeyError

**Comment by fergyfresh** [comment]
In the except
