### ISSUE TITLE
beginers dificulties, hostname

### ISSUE THREAD

**Issue by karolosz** [stevenleeg/geemusic#264]
hello i quite new, and not really advance

i have issue with seting the host name in 
i got issue with foreman giving me last info in console: " GET / HTTP/1.1" 404 -"
and when i testing alexa in alexa development console i have;
"I cannot resolve the hostname for the requested skill"

how should i set in .env
"# Google credentials
GOOGLE_EMAIL=k********@gmail.com
GOOGLE_PASSWORD=xxxxxxxxx

# Publicly accessible URL to your server, WITHOUT trailing slash
APP_URL=https://alexa-geemusic.stevegattuso.me

# Debug mode: Set to True or False
DEBUG_MODE=False"

thanx for helping
KaRol

**Comment by fergyfresh** [comment]
You need to setup your own server. He put his server to try to clear up the confusion people were having. The pre reqs are that you're familiar with atleast one of the deployment options.
