### ISSUE TITLE
ASK Music Skill API

### ISSUE THREAD

**Issue by evdev** [stevenleeg/geemusic#265]
Would it be possible to use the new API to build an Alexa app to interface directly with Google Play Music? https://developer.amazon.com/blogs/alexa/post/870491c3-0e95-4ea9-9e2e-ce1ae0cf0a79/now-available-use-the-ask-music-skill-api-to-stream-from-your-music-service-to-alexa-customers

**Comment by fergyfresh** [comment]
It could, but it's out of the scope of this project. You can use https://github.com/simon-weber/gmusicapi/ like we did here.
