### ISSUE TITLE
Tried all "Login unseccessfull" solution but still stuck on this error

### ISSUE THREAD

**Issue by mrecamales** [stevenleeg/geemusic#268]
I have followed the steps of the Heroku part, with a Google account with 2FA, generating an app password, and used this password in the GOOGLE_PASSWORD field.
![image](https://user-images.githubusercontent.com/23321033/48662741-bcde4280-ea86-11e8-8689-ce3ffd735608.png)
(I have replaced all the values with '*' just for the screenshot, but they are all set correctly).

But there's still the same error:

![image](https://user-images.githubusercontent.com/23321033/48662844-37f42880-ea88-11e8-97de-eb94412d59dc.png)

I should mention that my Google Music account is a free account, but I have uploaded a couple of songs.
I'm a very beginner on this (I beg you patience), may I modify the code or something?

**Comment by coggy9** [comment]
I'm having this issue with a paid account. Might be Google blocking Heroku logins, as I had [this](https://i.imgur.com/WwL0AaX.png) warning in my Google account after I tried to login a few times.

**Comment by MarioClot** [comment]
I've received the account warning too, but I thought it was not supposed to happen if you have a 2FA and an app password created

**Comment by coggy9** [comment]
I got it to work by using [this](https://accounts.google.com/b/0/DisplayUnlockCaptcha) page, and letting the app retry the login a few times.

**Comment by fergyfresh** [comment]
Yeah. there is a known bug in the upstream repo https://github.com/simon-weber/gmusicapi/issues/620. He has a fix on a dev branch and i'm going to roll it in to this once he irons it out or when I get around to it, whichever comes first.

**Comment by fergyfresh** [comment]
I got another implementation working on the `develop` branch. If you wanna try it out over there @coggy9

**Comment by gmarblestone** [comment]
@fergyfresh i got an error No module named 'fuzzywuzzy' on Heroku

**Comment by fergyfresh** [comment]
what branch?

**Comment by gmarblestone** [comment]
@fergyfresh develop

**Comment by fergyfresh** [comment]
you are right. i messed up, the fix is out `git pull origin develop`.

**Comment by gmarblestone** [comment]
@fergyfresh  thanks... ill check it out

**Comment by gmarblestone** [comment]
@fergyfresh hate to bother, but getting another error running now.  Thoughts on DEVICE_ID?

2018-12-06T22:00:47.454657+00:00 app[web.1]:     return cls(os.environ['DEVICE_ID'],
2018-12-06T22:00:47.454659+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/os.py", line 669, in __getitem__
2018-12-06T22:00:47.454999+00:00 app[web.1]:     raise KeyError(key) from None
2018-12-06T22:00:47.455006+00:00 app[web.1]: KeyError: 'DEVICE_ID'

**Comment by gmarblestone** [comment]
@fergyfresh my fault, you're right i didn't read.  So i was able to run the two python commands and the return was 
gmusicapi.exceptions.InvalidDeviceId: Invalid device_id <device_id>.Your valid device IDs are:
* ios:A02F50D4-5632-41BD-A0CF-xxxxxxxxx

So, i made a env = DEVICE_ID=A02F50D4-5632-41BD-A0CF-xxxxxxxxx

I still failed to authenticate... Any thoughts? did i use the correct device id?

Thanks again

**Comment by fergyfresh** [comment]
If I remember correctly theres something about device IDs in ios that you have to replace. I know that removing `ios` like you did is one of the steps. Maybe there is another step associated with removing dashes or something? Can any IOS users verify? @digiltd or anyone else? Look around for ios on open andclosed issues both here and at https://github.com/simon-weber/gmusicapi/ and see if you can drum up any info.
