### ISSUE TITLE
Skip to the # song in this album

### ISSUE THREAD

**Issue by PostsDesert** [stevenleeg/geemusic#28]
For this feature should it skip to the # song in the original album, or skip to the # song in the shuffled album say if shuffle is on?

**Comment by arimk** [comment]
Probably to the # song in the original album, as you don't know what # is really the song you want in the shuffled album :/
Anyway, thanks for you dedicated work, its really becoming even better than the regular alexa music skills :)

**Comment by alexbaucom17** [comment]
I agree with arimk. The # in the original album makes the most sense to me. Although if shuffle is on there are a couple ways you could handle that. You could find the requested song and go to it in the shuffled queue, which would discard any songs in the queue before that song. Or you just pull that song off of the queue, play it, and then resume the queue. Not sure if one of those is more favorable than the other...

**Comment by stevenleeg** [comment]
Yeah, +1 to @arimk's idea. We might want to also allow the user to specify the song by name, as that's probably a bit more natural than saying the track number.

Perhaps we could change the song selection intent to first check the queue for the given track name. If it's not present then we could proceed to search all of gmusic, as it currently does.

**Comment by PostsDesert** [comment]
Awesome, the track name search should be possible with a fuzzy search if we want to use a next intent (`ask gee music to skip to {track_name}`). I start on this as soon as the rest of my PR get figured out.

**Comment by PostsDesert** [comment]
Added to #75.
