### ISSUE TITLE
ImportError: No module named 'pip.req'

### ISSUE THREAD

**Issue by dony71** [stevenleeg/geemusic#282]
Error while running  pip3 install -r requirements.txt
...
....
Collecting Flask-Ask==0.9.8 (from -r requirements.txt (line 20))
  Using cached https://files.pythonhosted.org/packages/6a/f5/d4709ae94584a0b1541e9b52b2d25a8a1bdb6e2da9d6870f23fdd0523a30/Flask-Ask-0.9.8.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-c79l6boa/Flask-Ask/setup.py", line 8, in <module>
        from pip.req import parse_requirements
    ImportError: No module named 'pip.req'

**Comment by fergyfresh** [comment]
Flask-Ask is using `pip.req` module stuff which means you need pip <10.0.0 to install the packages.

**Comment by dony71** [comment]
thanks 
problem solved

**Comment by brandonjp** [comment]
For others having this issue:

  * The last pip before v10 was 9.0.3 - all pip versions are listed here: 
https://pypi.org/project/pip/#history

  * To install the specific version use: 
 `sudo pip install pip==9.0.3`  

  * Or... depending on your setup/environment, if you don't have access to sudo try: 
`python3 -m pip install pip==9.0.3`
