### ISSUE TITLE
Error after deploying via Lambda

### ISSUE THREAD

**Issue by MosiyukBohdan** [stevenleeg/geemusic#283]
I've deployed this project throw zappa on Ubuntu 18.04 Lts
So, I visit https://myurl.execute-api.us-east-2.amazonaws.com/dev and there is this error

"{'message': 'An uncaught exception happened while servicing this request. You can investigate this with the `zappa tail` command.', 'traceback': ['Traceback (most recent call last):\\n', '  File \"/var/task/handler.py\", line 452, in handler\\n    response = Response.from_app(self.wsgi_app, environ)\\n', '  File \"/var/task/werkzeug/wrappers.py\", line 903, in from_app\\n    return cls(*_run_wsgi_app(app, environ, buffered))\\n', '  File \"/var/task/werkzeug/test.py\", line 884, in run_wsgi_app\\n    app_rv = app(environ, start_response)\\n', \"TypeError: 'NoneType' object is not callable\\n\"]}"

**Comment by fergyfresh** [comment]
Whats the output of `zappa tail`

**Comment by fergyfresh** [comment]
Closing from lack of response.
