### ISSUE TITLE
TypeError: Can't compile non template nodes

### ISSUE THREAD

**Issue by dony71** [stevenleeg/geemusic#285]
try to restart foreman according to https://github.com/stevenleeg/geemusic/issues/206
but still keep having this error

01:19:50 web.1  | 127.0.0.1 - - [26/Mar/2019 01:19:50] "POST /alexa HTTP/1.1" 500 -
01:19:52 web.1  | Traceback (most recent call last):
01:19:52 web.1  |   File "/srv/alexa/lib/python3.5/site-packages/flask/app.py", line 1997, in __call__
01:19:52 web.1  |     return self.wsgi_app(environ, start_response)
01:19:52 web.1  |   File "/srv/alexa/lib/python3.5/site-packages/flask/app.py", line 1985, in wsgi_app
01:19:52 web.1  |     response = self.handle_exception(e)
01:19:52 web.1  |   File "/srv/alexa/lib/python3.5/site-packages/flask/app.py", line 1540, in handle_exception
01:19:52 web.1  |     reraise(exc_type, exc_value, tb)
01:19:52 web.1  |   File "/srv/alexa/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
01:19:52 web.1  |     raise value
01:19:52 web.1  |   File "/srv/alexa/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
01:19:52 web.1  |     response = self.full_dispatch_request()
01:19:52 web.1  |   File "/srv/alexa/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
01:19:52 web.1  |     rv = self.handle_user_exception(e)
01:19:52 web.1  |   File "/srv/alexa/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
01:19:52 web.1  |     reraise(exc_type, exc_value, tb)
01:19:52 web.1  |   File "/srv/alexa/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
01:19:52 web.1  |     raise value
01:19:52 web.1  |   File "/srv/alexa/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
01:19:52 web.1  |     rv = self.dispatch_request()
01:19:52 web.1  |   File "/srv/alexa/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
01:19:52 web.1  |     return self.view_functions[rule.endpoint](**req.view_args)
01:19:52 web.1  |   File "/srv/alexa/lib/python3.5/site-packages/flask_ask/core.py", line 767, in _flask_view_func
01:19:52 web.1  |     result = self._map_intent_to_view_func(self.request.intent)()
01:19:52 web.1  |   File "/home/hts/geemusic/geemusic/intents/selection.py", line 18, in help
01:19:52 web.1  |     text = render_template("help_text")
01:19:52 web.1  |   File "/srv/alexa/lib/python3.5/site-packages/flask/templating.py", line 133, in render_template
01:19:52 web.1  |     return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
01:19:52 web.1  |   File "/srv/alexa/lib/python3.5/site-packages/jinja2/environment.py", line 869, in get_or_select_template
01:19:52 web.1  |     return self.get_template(template_name_or_list, parent, globals)
01:19:52 web.1  |   File "/srv/alexa/lib/python3.5/site-packages/jinja2/environment.py", line 830, in get_template
01:19:52 web.1  |     return self._load_template(name, self.make_globals(globals))
01:19:52 web.1  |   File "/srv/alexa/lib/python3.5/site-packages/jinja2/environment.py", line 804, in _load_template
01:19:52 web.1  |     template = self.loader.load(self, name, globals)
01:19:52 web.1  |   File "/srv/alexa/lib/python3.5/site-packages/jinja2/loaders.py", line 125, in load
01:19:52 web.1  |     code = environment.compile(source, name, filename)
01:19:52 web.1  |   File "/srv/alexa/lib/python3.5/site-packages/jinja2/environment.py", line 581, in compile
01:19:52 web.1  |     defer_init=defer_init)
01:19:52 web.1  |   File "/srv/alexa/lib/python3.5/site-packages/jinja2/environment.py", line 543, in _generate
01:19:52 web.1  |     optimized=self.optimized)
01:19:52 web.1  |   File "/srv/alexa/lib/python3.5/site-packages/jinja2/compiler.py", line 78, in generate
01:19:52 web.1  |     raise TypeError('Can\'t compile non template nodes')
01:19:52 web.1  | TypeError: Can't compile non template nodes

**Comment by fergyfresh** [comment]
Still having this issue? I just tried deploying it again and didn't have an issue.

What version of python are you using?

**Comment by fergyfresh** [comment]
Closing for lack of follow up.

**Comment by stridger** [comment]
I am having the same issue, I'm afraid. Tried various things like different Python version etc, but cannot seem to fix it :(

**Comment by fergyfresh** [comment]
`"/srv/alexa/lib/python3.5/site-packages/jinja2/compiler.py"` I'm using python3.6 and the tests run fine for me. Try with python3.6

**Comment by stridger** [comment]
I tried python 3.5, 3.6 and 3.7. Always the same error. Interestingly I get the dependency inconsistency issues below when installing the requirements in the virtual environment...

ERROR: flask-ask 0.9.8 has requirement aniso8601==1.2.0, but you'll have aniso8601 1.2.1 which is incompatible.
ERROR: flask-ask 0.9.8 has requirement Flask==0.12.1, but you'll have flask 0.12.2 which is incompatible.
ERROR: flask-ask 0.9.8 has requirement pyOpenSSL==17.0.0, but you'll have pyopenssl 17.2.0 which is incompatible.
ERROR: flask-ask 0.9.8 has requirement PyYAML==3.12, but you'll have pyyaml 3.13 which is incompatible.
ERROR: flask-ask 0.9.8 has requirement six==1.11.0, but you'll have six 1.10.0 which is incompatible.
ERROR: zappa 0.45.1 has requirement PyYAML==3.12, but you'll have pyyaml 3.13 which is incompatible.
ERROR: zappa 0.45.1 has requirement six>=1.11.0, but you'll have six 1.10.0 which is incompatible.
ERROR: zappa 0.45.1 has requirement Werkzeug==0.12, but you'll have werkzeug 0.12.2 which is incompatible.

**Comment by stridger** [comment]
Here is my Traceback:

22:03:35 web.1  | Traceback (most recent call last):   
22:03:35 web.1  |   File "/local/www/secure/geemusic/.venv/lib/python3.6/site-packages/flask/app.py", line 1997, in __call__
22:03:35 web.1  |     return self.wsgi_app(environ, start_response)
22:03:35 web.1  |   File "/local/www/secure/geemusic/.venv/lib/python3.6/site-packages/flask/app.py", line 1985, in wsgi_app
22:03:35 web.1  |     response = self.handle_exception(e)
22:03:35 web.1  |   File "/local/www/secure/geemusic/.venv/lib/python3.6/site-packages/flask/app.py", line 1540, in handle_exception
22:03:35 web.1  |     reraise(exc_type, exc_value, tb) 
22:03:35 web.1  |   File "/local/www/secure/geemusic/.venv/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
22:03:35 web.1  |     raise value
22:03:35 web.1  |   File "/local/www/secure/geemusic/.venv/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
22:03:35 web.1  |     response = self.full_dispatch_request()
22:03:35 web.1  |   File "/local/www/secure/geemusic/.venv/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
22:03:35 web.1  |     rv = self.handle_user_exception(e)
22:03:35 web.1  |   File "/local/www/secure/geemusic/.venv/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
22:03:35 web.1  |     reraise(exc_type, exc_value, tb)
22:03:35 web.1  |   File "/local/www/secure/geemusic/.venv/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
22:03:35 web.1  |     raise value
22:03:35 web.1  |   File "/local/www/secure/geemusic/.venv/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
22:03:35 web.1  |     rv = self.dispatch_request()
22:03:35 web.1  |   File "/local/www/secure/geemusic/.venv/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
22:03:35 web.1  |     return self.view_functions[rule.endpoint](**req.view_args)
22:03:35 web.1  |   File "/local/www/secure/geemusic/.venv/lib/python3.6/site-packages/flask_ask/core.py", line 767, in _flask_view_func
22:03:35 web.1  |     result = self._map_intent_to_view_func(self.request.intent)()
22:03:35 web.1  |   File "/local/www/secure/geemusic/geemusic/intents/selection.py", line 122, in play_song
22:03:35 web.1  |     return statement(render_template("no_song"))
22:03:35 web.1  |   File "/local/www/secure/geemusic/.venv/lib/python3.6/site-packages/flask/templating.py", line 133, in render_template
22:03:35 web.1  |     return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
22:03:35 web.1  |   File "/local/www/secure/geemusic/.venv/lib/python3.6/site-packages/jinja2/environment.py", line 869, in get_or_select_template
22:03:35 web.1  |     return self.get_template(template_name_or_list, parent, globals)
22:03:35 web.1  |   File "/local/www/secure/geemusic/.venv/lib/python3.6/site-packages/jinja2/environment.py", line 830, in get_template
22:03:35 web.1  |     return self._load_template(name, self.make_globals(globals))
22:03:35 web.1  |   File "/local/www/secure/geemusic/.venv/lib/python3.6/site-packages/jinja2/environment.py", line 804, in _load_template
22:03:35 web.1  |     template = self.loader.load(self, name, globals)
22:03:35 web.1  |   File "/local/www/secure/geemusic/.venv/lib/python3.6/site-packages/jinja2/loaders.py", line 125, in load
22:03:35 web.1  |     code = environment.compile(source, name, filename)
22:03:35 web.1  |   File "/local/www/secure/geemusic/.venv/lib/python3.6/site-packages/jinja2/environment.py", line 581, in compile
22:03:35 web.1  |     defer_init=defer_init)
22:03:35 web.1  |   File "/local/www/secure/geemusic/.venv/lib/python3.6/site-packages/jinja2/environment.py", line 543, in _generate
22:03:35 web.1  |     optimized=self.optimized)
22:03:35 web.1  |   File "/local/www/secure/geemusic/.venv/lib/python3.6/site-packages/jinja2/compiler.py", line 78, in generate
22:03:35 web.1  |     raise TypeError('Can\'t compile non template nodes')
22:03:35 web.1  | TypeError: Can't compile non template nodes

**Comment by stridger** [comment]
OK, got it. The LANGUAGE environment variable by default on Ubuntu is en_US or en_GB etc, the app however expects just "en" or "fr" etc. So setting this correct makes it find the templates and makes it work.
