### ISSUE TITLE
Docker image won't start

### ISSUE THREAD

**Issue by WayneManion** [stevenleeg/geemusic#288]
I've been running Gee Music for several months, but all of a sudden it quit working. I looked and saw that the Docker image wasn't running, and when I try to run it, I get this:

$ sudo docker run geemusic
19:53:08 web.1  | started with pid 8
19:53:10 web.1  | Traceback (most recent call last):
19:53:10 web.1  |   File "server.py", line 1, in <module>
19:53:10 web.1  |     from geemusic import app
19:53:10 web.1  |   File "/geemusic/geemusic/__init__.py", line 30, in <module>
19:53:10 web.1  |     api = GMusicWrapper.generate_api(logger=app.logger)
19:53:10 web.1  |   File "/geemusic/geemusic/utils/music.py", line 274, in generate_api
19:53:10 web.1  |     **kwargs)
19:53:10 web.1  |   File "/geemusic/geemusic/utils/music.py", line 14, in __init__
19:53:10 web.1  |     success = self._api.login(username, password, getenv('ANDROID_ID', Mobileclient.FROM_MAC_ADDRESS))
19:53:10 web.1  |   File "/usr/lib/python3.6/site-packages/gmusicapi/clients/mobileclient.py", line 139, in login
19:53:10 web.1  |     if not self.session.login(email, password, device_id):
19:53:10 web.1  |   File "/usr/lib/python3.6/site-packages/gmusicapi/session.py", line 191, in login
19:53:10 web.1  |     res = gpsoauth.perform_master_login(email, password, android_id)
19:53:10 web.1  |   File "/usr/lib/python3.6/site-packages/gpsoauth/__init__.py", line 60, in perform_master_login
19:53:10 web.1  |     'EncryptedPasswd': google.signature(email, password, android_key_7_3_29),
19:53:10 web.1  |   File "/usr/lib/python3.6/site-packages/gpsoauth/google.py", line 50, in signature
19:53:10 web.1  |     encrypted_login = cipher.encrypt((email + u'\x00' + password).encode('utf-8'))
19:53:10 web.1  | TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
19:53:10 web.1  | exited with code 1
19:53:10 system | sending SIGTERM to all processes

Does all of this mean login error?

**Comment by fergyfresh** [comment]
I think you must have set those environment variables within the context of your current terminal. If you `echo $GOOGLE_EMAIL` I bet those env vars are blank.

**Comment by fergyfresh** [comment]
Closed because of inactivity.
