### ISSUE TITLE
setup-tools

### ISSUE THREAD

**Issue by MadDucks** [stevenleeg/geemusic#29]
You might want to add in the documentation, that if you have an older Python install, and it's erring out on setup-tools, to do the following in the virtualenv

pip install -U pip wheel setuptools

**Comment by stevenleeg** [comment]
This is something that's a bit unique to certain installations so, for simplicity's sake, I think I'll leave it out of the documentation for now. If there are others that are getting tripped up on this feel free to drop a comment or +1 here and I'll reconsider.

Regardless, thanks for letting me know!
