### ISSUE TITLE
Heroku Setup

### ISSUE THREAD

**Issue by huberf** [stevenleeg/geemusic#3]
I have successfully set this up on Heroku, and think it could be valuable to add a description of how to do this in the README. It only took adding my Google account information to the Heroku environment variables dashboard instead of my local environment file and modifying the server.py file to include this modified line: `app.run(host="0.0.0.0", port=int(os.environ["PORT"]), debug=True)`

This could be a simple but valuable addition, as the barrier to contributors entry would likely be reduced.

If this sounds like it would be useful, I can open a PR for the README addition.

**Comment by stevenleeg** [comment]
👍  sounds great, feel free to open!
