### ISSUE TITLE
Bad Remote Endpoint in Amazon Developer Console

### ISSUE THREAD

**Issue by gabeduke** [stevenleeg/geemusic#32]
I'm trying to build the service behind a firewall and am receiving `The remote endpoint could not be called, or the response it returned was invalid.` from amazon. Here are the steps I've taken so far:

* I signed up for ngrok so I could have a stable URL to give amazon, but was unable to get it to run as a daemon. It does work if I spin it up as a foreground instance but I would rather not pay for the service anyways.

* Attempted to use a self-signed cert and then modified the server.py file to use the following config. I was able to hit this end point through the browser and received the expected warning message. I also see the GET request in the server log.
```
from geemusic import app
import os

if __name__ == '__main__':
    port = int(os.environ.get("PORT", 4000))

context = ('[path]/certificate.pem', '[path]/private-key.pem')
app.run(host='0.0.0.0', port=port, debug=True) #, ssl_context=context).
```

* Then I tried using `letsencrypt` to add a trusted cert to my server and am able to hit the endpoint in the browser but only on http. Then I forced the certificate path using the above configuration which allowed it to work over https. Now in my server log I'm getting `192.168.1.1 - - [11/Jan/2017 15:08:37] "GET /alexa HTTP/1.1" 405 -` However I'm still returning the original error when I attempt to call the same endpoint from amazon

I'm also curious what the point is of running the server through foreman since all it does is call the server. Is there an advantage to doing it this way? I've been spinning up the server directly through python.

Any ideas are appreciated, thanks!

**Comment by PostsDesert** [comment]
For ngrok, I use something like Screen or Tmux (two terminal management programs) to easily keep it in the foreground. From what I can tell foreman is used to load the `.env` file which stores your google credentials. I have no idea on the advantages though.

**Comment by alexbaucom17** [comment]
I also use tmux to keep ngrok running in the foreground and it has worked great for me. I just accept the fact that if my server power cycles I have to run through a few setup steps again. But then I don't have to pay so it works for me. Here's my setup steps, in case it is useful (I just stuck all this in a text file on the server to remind me how to do this down the road when I inevitably forget):

Open session and start ngrok:
	tmux new -s ngrok
	./ngrok http 5000
	Copy ngrok address
	Disconnect with Ctl+b then d

Paste ngrok address into ~/geemusic/.env
Paste ngrox address (with /alexa at the end) into amazon developer console under configuration tab

Open session and start server
	tmux new -s server
	cd geemusic
	foreman start
	Disconnect with Ctl+b then d

Test server on amazon developer test section
If needed, connect to tmux sessions with tmux a -t <name>

**Comment by gabeduke** [comment]
Thanks - I may have to do the same as I'm about out of ideas to turn this into a service. It appears that letsencrypt is supported, so that shouldn't be the problem. When I hit the URL in my browser it shows as secure and I see the GET request in the server log. However I'm still getting `The remote endpoint could not be called, or the response it returned was invalid.' in the Service Simulator. I'm at pretty much a dead end until I can get a better error message.

Regarding foreman doh! I should have remembered that. I was too busy messing w/ the endpoint I didn't realize that even though the server was up, it wouldn't have authenticated!

Anyways thanks for the tmux instructions!

**Comment by stevenleeg** [comment]
Going to close this, as this seems like more of an issue with setup than the library itself. Thanks for handling this @PostsDesert and @alexbaucom17!

**Comment by Mutate** [comment]
I keep getting "There was an error calling the remote endpoint, which returned HTTP 503 : Service Unavailable" when trying to test in the Amazon Alexa service simulator.  I built the app in Heroku following the instructions.  I rebuilt the app multiple times with the same result.  Any ideas?
