### ISSUE TITLE
Feature Request: Shuffle All Songs

### ISSUE THREAD

**Issue by dhruv4** [stevenleeg/geemusic#35]
Hey man! As a newbie to Alexa skills, this is a SUPER cool skill to mess around with. Can you make an intent to shuffle all uploaded/purchased songs?

Thanks :)

**Comment by PostsDesert** [comment]
A shuffle intent has been implemented already. So you want an intent to play songs from your library? For example you would say, `Alexa tell gee music to play songs from my library`.

**Comment by PostsDesert** [comment]
Added to #47.
