### ISSUE TITLE
Troubleshooting guide?

### ISSUE THREAD

**Issue by nycedwardd** [stevenleeg/geemusic#37]
I've set it up, and it appears to work until I play something. There's a warning message after the initial request, and then it appears to work properly. When I ask echo to play, I see the connection to the server process and echo reports that it is playing music from my personalized station, but no music actually plays.

I am running the server on an AWS image. ngnix is set to proxy requests to /alexa over to port localhost:4000 and it does connect properly.

APP_URL=https://<my server>/alexa

```
 * Running on http://127.0.0.1:4000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger pin code: 103-857-125
/usr/local/lib64/python2.7/site-packages/Cryptodome/Math/_Numbers_gmp.py:230: UserWarning: implicit cast to 'char *' from a different pointer type: will be forbidden in the future (check that the types are as you expect; use an explicit ffi.cast() if they are correct)
  _gmp.gmp_snprintf(buf, c_size_t(buf_len), b("%Zd"), self._mpz_p)
127.0.0.1 - - [14/Jan/2017 18:03:43] "POST /alexa HTTP/1.0" 200 -
127.0.0.1 - - [14/Jan/2017 18:04:38] "POST /alexa HTTP/1.0" 200 -
127.0.0.1 - - [14/Jan/2017 18:04:38] "GET /alexa/stream/Tkhmsodqmlo74qsujirn4obuzj4 HTTP/1.0" 404 -
127.0.0.1 - - [14/Jan/2017 18:04:38] "POST /alexa HTTP/1.0" 400 -
127.0.0.1 - - [14/Jan/2017 18:05:01] "POST /alexa HTTP/1.0" 200 -
127.0.0.1 - - [14/Jan/2017 18:05:15] "POST /alexa HTTP/1.0" 200 -
127.0.0.1 - - [14/Jan/2017 18:05:15] "GET /alexa/stream/T4qej3geoetgltexgwpyt4ftktm HTTP/1.0" 404 -
127.0.0.1 - - [14/Jan/2017 18:05:16] "POST /alexa HTTP/1.0" 400 -

```

**Comment by stevenleeg** [comment]
This sounds/looks like an issue with your `APP_URL`. Remember that it should look something like this in your `.env` file:

```
APP_URL=https://ff9b5cce.ngrok.io
```

Note that there is no trailing slash or `/alexa` after the domain. Feel free to re-open if this doesn't solve your issue.

**Comment by nycedwardd** [comment]
Thanks for such a fast response. I had tried that as well, I think there was a problem with the proxy config, I set it up on a new host instead of sharing it with another web server. It works well, but often the voice service will send the request to Pandora or play it through Amazon music before it ever hits Geemusic.
