### ISSUE TITLE
Card Support

### ISSUE THREAD

**Issue by PostsDesert** [stevenleeg/geemusic#39]
It would be nice to have card support with images now that we have reliable track metadata. I would be happy to implement this once my current PR get worked out.

**Comment by stevenleeg** [comment]
Yeah this would be great. I think it'd be best to send along the album art + the artist/album/track details. 

This would be especially useful for the "play some music" intent.

**Comment by PostsDesert** [comment]
Can you give some examples for track details? So far i'm thinking title and artist.

**Comment by stevenleeg** [comment]
Yup! Title, artist, and album seem like they'd be sufficient.

**Comment by PostsDesert** [comment]
added to #41.
