### ISSUE TITLE
Alexa isn't playing music with error message: "Store tracks require a subscription to stream."

### ISSUE THREAD

**Issue by dhruv4** [stevenleeg/geemusic#42]
Hey!

If I try to play my I'm Feeling Lucky playlist, Gee Music thinks it's playing something (if I ask "what song is this?" it'll give me an answer), but no audio is being played. So, I've gone through the error logs and have traced this back to the "get_stream_url" method. Is it possible that Gee Music is not searching through my uploaded songs, but rather it's going straight to store tracks?

Separately, I'm unable to play tracks from my own library because the search method is coming up blank, although the index_library function is working fine. I found a potentially relevant issue here: https://github.com/simon-weber/gmusicapi/issues/474. 

For reference, I'm on a free tier account in the US and have been unable to get any audio to play.

Thanks!

**Comment by stevenleeg** [comment]
@PostsDesert has worked with this a bit more than I, so maybe he can correct me if I'm wrong but I think you're right that we're simply skipping the library in favor of store tracks (which you're unable to play).

I'm away from my Dot right now but I do think this is a bug that we should address.

**Comment by PostsDesert** [comment]
Yep, it's set up to use a store track whenever possible (library tracks are a pain to work with.) A lot of the GMusicAPI calls will not retrieve user uploaded tracks (I know the search one won't). From the GMusicAPI docs it looks like IFL radio returns a list of store songs so there's no way we could get the user uploaded version. A potential solution is to add a `play library tracks` intent which was suggested in #35 which for you I would assume would play user uploaded tracks.

**Comment by SewerSide666** [comment]
I made a workaround to using store tracks as I'm a free user, it's not pretty though! See https://www.reddit.com/r/amazonecho/comments/5l47db/geemusic_a_skill_that_allows_alexa_to_stream_from/dch02n0/

**Comment by dhruv4** [comment]
@SewerSide666 after a bit of finagling around with it so that it mostly worked with the more updated code I got the "play song <name> by <artist>" intent working! So that's something! The rest is not working, however.

@PostsDesert, @stevenleeg thanks for your responses! I will try working on this issue myself and hopefully we find a solution :)

**Comment by stevenleeg** [comment]
Sounds good. Feel free to fork/create a PR if you'd like to share the results!

**Comment by PostsDesert** [comment]
I made a PR for a library intent which should let free tiered accounts play songs from their library. #47

**Comment by and3rson** [comment]
Related: and3rson/clay#3
