### ISSUE TITLE
Would we want to add a feature for a setlist.fm wrapper I made last year?

### ISSUE THREAD

**Issue by fergyfresh** [stevenleeg/geemusic#45]
https://github.com/fergyfresh/setlist-on-a-playlist/blob/master/setlistfm.py

Basically it would require some clean-up but I know people that would want to use it.

I could add an intent to play a bands most recent setlist which I like to do sometimes because they are usually pretty good playlists. My friend REALLY likes it cause he likes to know exactly which portion of which albums they have been playing recently and he will only listen to setlist playlists that he makes manually. This would do it for you!!!!

**Comment by fergyfresh** [comment]
requests and beautifulsoup are already dependencies so we could just have the file live in this repo.

**Comment by stevenleeg** [comment]
Hmm this might be a bit too specific of a feature for the project in its current state. I don't know that there's a big enough demand for this kind of integration just yet, but if there are more requests I'm happy to reconsider.

**Comment by fergyfresh** [comment]
I'll just keep it in an up to date fork. It's nbd
