### ISSUE TITLE
Docker Support

### ISSUE THREAD

**Issue by kuruoujou** [stevenleeg/geemusic#55]
> If you're looking to implement a feature, please open an issue before creating a PR so I can review it and make sure it's something that should be added.

Okay!

I use containers to host individual servers I use locally, so I'd like to have this running in a container. I've already built this into a container locally, so I'd like to contribute the Dockerfile back upstream. It's written based on the instructions you have here.

Then, if you wanted to, you could create an account on the docker hub and have it run a DTR automatically on changes to the repository, so that it would always be up to date, and people could download it with "docker pull stevenleeg/geemusic:latest" or something similar.

If you'd like to see what I've written, I have it here: https://github.com/kuruoujou/geemusic/blob/docker/Dockerfile

**Comment by blmr** [comment]
That's a great idea! I built a local docker image and have to rebuild it from time to time. Having the official image on DockerHub will save people some time on setting up Dev environment.

**Comment by stevenleeg** [comment]
Dockerfile sounds good to me :+1: feel free to PR!
