### ISSUE TITLE
Question regarding Google Authentication

### ISSUE THREAD

**Issue by alexbaucom17** [stevenleeg/geemusic#6]
First off, thank you very much for creating this project! I got an echo dot for Christmas and really wanted to make it work with Google Play Music so this is perfect!

However, I am having an issue with the server crashing when trying to authenticate with my Google credentials. I do have two step authentication turned on for my account so I suspect that is the culprit, but you seem to indicate that the server will still work with two-step in the readme. I was unsure what you mean by 'application specific password' so used my normal password, which might be the issue. Is there something I am missing here? Thanks!

**Comment by huberf** [comment]
This article explains how to setup an application specific password. https://support.google.com/accounts/answer/185833?hl=en

**Comment by alexbaucom17** [comment]
Perfect! That is exactly what I need. Thanks for such a quick reply!
