### ISSUE TITLE
Code 400/HTTP 0.9 Bad Request Error

### ISSUE THREAD

**Issue by houseofbugs** [stevenleeg/geemusic#62]
I am running this on a fresh installation and ports are forwarded. I am getting these errors and it is not working at all:

![mstsc_2017-02-03_20-04-51](https://cloud.githubusercontent.com/assets/25088191/22614728/0cc54312-ea4c-11e6-8c7d-2e8243b01ff3.png)

![chrome_2017-02-03_20-05-13](https://cloud.githubusercontent.com/assets/25088191/22614732/18991826-ea4c-11e6-9b98-d5de63d1b231.png)

**Comment by stevenleeg** [comment]
Hmm, I've never seen anything like this before but I have a hunch that it has something to do with character encoding in Windows.

Unless this can be reproduced on a *nix platform there's not much I can do, as Windows is not a supported platform. I'd recommend spinning up a vm or vps and trying to run it from there.

**Comment by houseofbugs** [comment]
Why did you close this? I said it is running in a VM with Ubuntu Server 16.04 LTS.

**Comment by digiltd** [comment]
Could it be vpn related?

**Comment by fonziedave** [comment]
I have the same error with raspbian. But I can't get my self signed certificate to be properly recognized in the Amazon SSL menu. It is always greyed out so I'm not sure if there is a problem with the uploaded certificate itself. Could you solve your problem with the Bad Request Error_

**Comment by fonziedave** [comment]
solved - source: https://www.reddit.com/r/amazonecho/comments/5l47db/geemusic_a_skill_that_allows_alexa_to_stream_from/

> You will need to modify the server.py file so that it starts Flask up with an SSL context.
Mine looks like:
from geemusic import app import os
import ssl
if name == 'main': port = int(os.environ.get("PORT", 4000)) app.run(host='0.0.0.0', port=port, debug=True, ssl_context=('/opt/geemusic/certificate.pem', '/opt/geemusic/private-key.pem'))
Obviously change it to point to your certificate and key.
