### ISSUE TITLE
"Unrecognized Device" from Heroku

### ISSUE THREAD

**Issue by jMCHammer** [stevenleeg/geemusic#64]
Upon startup of your Heroku server, it's likely to be flagged as an "Unrecognized Device" by Google. From the logs, it appears to be a sign-in failure. You can fix this issue by adding the device here https://myaccount.google.com/device-activity .

I was thinking it might be a good idea to update the Heroku section in the README with this information.

**Comment by stevenleeg** [comment]
sorry for the delay, I've been crazy busy lately. 

this seems like a reasonable note to add to the README. since you've encountered it would you mind submitting a PR to add it in?

**Comment by stevenleeg** [comment]
This hasn't seen any recent activity and will therefore be closed. Feel free to comment or file a new issue if you're still having trouble.
