### ISSUE TITLE
Heroku not starting

### ISSUE THREAD

**Issue by arimk** [stevenleeg/geemusic#68]
Just pulled the last version that should have fixed the not working music bug, but instead I have now in the logs:

2017-02-22T21:02:35.024974+00:00 heroku[web.1]: Starting process with command `python3 server.py`
2017-02-22T21:02:36.978075+00:00 app[web.1]: Fatal Python error: Py_Initialize: Unable to get the locale encoding
2017-02-22T21:02:36.978103+00:00 app[web.1]: ImportError: No module named 'encodings'
2017-02-22T21:02:37.043637+00:00 heroku[web.1]: Process exited with status 134
2017-02-22T21:02:37.053966+00:00 heroku[web.1]: State changed from starting to crashed

Seemed ok when I built :/

remote: Building source:
remote:
remote: -----> Python app detected
remote:      $ pip install -r requirements.txt
remote:        Collecting Flask-Ask==0.8.7 (from -r /tmp/build_4b61312cbf8d848f0b869fba166dc3f3/requirements.txt (line 10))
remote:          Downloading Flask-Ask-0.8.7.tar.gz
remote:        Collecting gmusicapi==10.1.1 (from -r /tmp/build_4b61312cbf8d848f0b869fba166dc3f3/requirements.txt (line 13))
remote:          Downloading gmusicapi-10.1.1.tar.gz (165kB)
remote:        Installing collected packages: Flask-Ask, gmusicapi
remote:          Found existing installation: Flask-Ask 0.8.4
remote:            Uninstalling Flask-Ask-0.8.4:
remote:              Successfully uninstalled Flask-Ask-0.8.4
remote:          Running setup.py install for Flask-Ask: started
remote:            Running setup.py install for Flask-Ask: finished with status 'done'
remote:          Found existing installation: gmusicapi 10.1.0
remote:            Uninstalling gmusicapi-10.1.0:
remote:              Successfully uninstalled gmusicapi-10.1.0
remote:          Running setup.py install for gmusicapi: started
remote:            Running setup.py install for gmusicapi: finished with status 'done'
remote:        Successfully installed Flask-Ask-0.8.7 gmusicapi-10.1.1
remote:
remote: -----> Discovering process types
remote:        Procfile declares types -> web
remote:
remote: -----> Compressing...
remote:        Done: 51M
remote: -----> Launching...
remote:        Released v12

**Comment by apsco** [comment]
To fix this I had to create a file called runtime.txt with the text "python-3.6.0" in it. 
Once I added that file to my local git repo and pushed it to a new heroku instance it all worked. 
By default heroku uses python 2 which doesn't work.

**Comment by arimk** [comment]
You should do a pull request on this!

**Comment by arimk** [comment]
added it in #71
