### ISSUE TITLE
free google music tier

### ISSUE THREAD

**Issue by davx8342** [stevenleeg/geemusic#70]
Same issue as #50 where everything seems to be connected ok, but as soon as I try and play a song or album I know I have in my library I get the dreaded "Sorry, I couldn't find that artist". Which I gather is down to me using the free Google Music tier.

The PR in #50 leads to a 404, but I installed the branch and there seem to be the following sample utterances : 

GeeMusicPlayLibraryIntent play songs from my library
GeeMusicPlayLibraryIntent play tracks from my library
GeeMusicPlayLibraryIntent play my library
GeeMusicPlayLibraryIntent start playing tracks from my library
GeeMusicPlayLibraryIntent play songs from library

So would I be right in saying, at this time, there's no way of playing specific songs from your library if you have the free tier?

**Comment by PostsDesert** [comment]
The PR has been merged with master. On master does `GeeMusicPlayLibraryIntent` not work? Do you have the latest version of `gmusicapi` which adds some basic support for free accounts?

**Comment by grahamboyd** [comment]
pip says I'm using 10.1.1, latest seems to be 10.1.2rc1 ?

Sorry, should have also mentioned previously that I'm using it in a non-US territory.

**Comment by PostsDesert** [comment]
Ohh, I mistook the original question. Yes as of right now there is no way to choose a specific song from your library. There's a request to be able to skip to a certain song by the name that may partly solve your issue once it gets implemented.

**Comment by PostsDesert** [comment]
I'll added skip support to #75.

**Comment by stevenleeg** [comment]
Closing this. Feel free to re-open if there is more to discuss here.
