### ISSUE TITLE
Python Socket Error

### ISSUE THREAD

**Issue by Shaun87** [stevenleeg/geemusic#74]
I am struggling with starting the server. When I run Foreman, I get the following error:

pi@raspberrypi:~/geemusic $ foreman start
13:27:36 web.1  | started with pid 4504
13:27:45 web.1  | /usr/local/lib/python3.4/dist-packages/Cryptodome/Math/_Numbers_gmp.py:230: UserWarning: implicit cast to 'char *' from a different pointer type: will be forbidden in the future (check that the types are as you expect; use an explicit ffi.cast() if they are correct)
13:27:45 web.1  |   _gmp.gmp_snprintf(buf, c_size_t(buf_len), b("%Zd"), self._mpz_p)
13:27:45 web.1  | Traceback (most recent call last):
13:27:45 web.1  |   File "server.py", line 6, in <module>
13:27:45 web.1  |     app.run(host='0.0.0.0', port=port, debug=True)
13:27:45 web.1  |   File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 841, in run
13:27:45 web.1  |     run_simple(host, port, self, **options)
13:27:45 web.1  |   File "/usr/local/lib/python3.4/dist-packages/werkzeug/serving.py", line 677, in run_simple
13:27:45 web.1  |     s.bind((hostname, port))
13:27:45 web.1  | **OSError: [Errno 98] Address already in use**
13:27:45 web.1  | --------------------------------------------------------------------------------
13:27:45 web.1  | DEBUG in music [/home/pi/geemusic/geemusic/utils/music.py:57]:
13:27:45 web.1  | Done! Discovered 39 tracks.
13:27:45 web.1  | --------------------------------------------------------------------------------
13:27:46 web.1  | exited with code 1
13:27:46 system | sending SIGTERM to all processes

Please help.
Thanks in advance

**Comment by stevenleeg** [comment]
That error means that there is another service using the same port that geemusic is trying to bind to. Make sure you're not running two instances of the command.

**Comment by Shaun87** [comment]
Hi Steven

I used **netstat -plunt** and found that nothing is using the port.

I made the following change in server.py and it seems to be working:
app.run(host='0.0.0.0', port=4000, debug=True)

I just want to make sure that I won't run into any issues by doing this.

Thank you
