### ISSUE TITLE
When Alexa wakes up, music pauses instead of going to background.

### ISSUE THREAD

**Issue by joseeantonior** [stevenleeg/geemusic#76]
Whenever I wake Alexa up to issue a command and music is playing, the music just pauses.

Steps to reproduce:
1.- Start playing music from geemusic
2.- Call "Alexa" or whatever your wake word is.

Expected result: Alexa will start listening, but the music will still play in the background, with a lower volume.

Actual result: Alexa starts listening, but music pauses. Music resumes from where it was as soon as Alexa goes back to sleep.

**Comment by PostsDesert** [comment]
This is how flask-ask handles the request. You could try making an issue [there](https://github.com/johnwheeler/flask-ask/issues). It may be a limitation of the Alexa skill service though.

**Comment by joseeantonior** [comment]
Issue x-posted there. Feel free to close this issue.
