### ISSUE TITLE
Deploying on Heroku with the free Google Music

### ISSUE THREAD

**Issue by AGT89** [stevenleeg/geemusic#79]
I've managed to set this up on my Echo Dot following the (UK English) instructions to deploy it to Heroku but I can't get it to play any music.

When I ask it to "play artist x" that I know is in my library of uploaded music I just get "Sorry, I couldn't find that artist" with the following couple of lines in the Heroku log:

> 2017-03-18T09:30:26.140721+00:00 heroku[router]: at=info method=POST path="/alexa" host=xxx.herokuapp.com request_id=f93d31ec-9785-46f4-9f40-dbdef4458626 fwd="72.21.217.152" dyno=web.1 connect=1ms service=389ms status=200 bytes=324 protocol=https
> 2017-03-18T09:30:26.140632+00:00 app[web.1]: 10.158.177.57 - - [18/Mar/2017 09:30:26] "POST /alexa HTTP/1.1" 200 -

Similarly for "play album by artist" I just get "Sorry, I couldn't find that album" with the following log:

> 2017-03-18T09:35:24.171038+00:00 app[web.1]: --------------------------------------------------------------------------------
> 2017-03-18T09:35:24.171051+00:00 app[web.1]: DEBUG in selection [/app/geemusic/intents/selection.py:59]:
> 2017-03-18T09:35:24.171053+00:00 app[web.1]: Fetching album x by x
> 2017-03-18T09:35:24.171057+00:00 app[web.1]: --------------------------------------------------------------------------------
> 2017-03-18T09:35:24.588372+00:00 heroku[router]: at=info method=POST path="/alexa" host=xxx.herokuapp.com request_id=c2e32f46-b340-46b5-9dab-4d79618e8f83 fwd="72.21.217.130" dyno=web.1 connect=1ms service=525ms status=200 bytes=323 protocol=https
> 2017-03-18T09:35:24.586878+00:00 app[web.1]: 10.63.231.107 - - [18/Mar/2017 09:35:24] "POST /alexa HTTP/1.1" 200 -

I saw #70 so tried just "play my library" and got the response "Playing music from your library" with the following in the Heroku logs but nothing played:

> 2017-03-18T09:44:53.829490+00:00 heroku[router]: at=info method=POST path="/alexa" host=xxx.herokuapp.com request_id=21c25813-c4dc-42dd-b7ef-d9e45bf78aaa fwd="54.240.197.74" dyno=web.1 connect=0ms service=31ms status=200 bytes=565 protocol=https
> 2017-03-18T09:44:53.828238+00:00 app[web.1]: 10.30.24.121 - - [18/Mar/2017 09:44:53] "POST /alexa HTTP/1.1" 200 -
> 2017-03-18T09:44:54.905617+00:00 heroku[router]: at=info method=GET path="/alexa/stream/Tazlwyae6couyno5qs5aum6jsty" host=xxx.herokuapp.com request_id=a108b2c3-0f46-4b43-b3df-d301edc986f1 fwd="81.147.64.54" dyno=web.1 connect=1ms service=20ms status=500 bytes=25870 protocol=https
> 2017-03-18T09:44:54.900730+00:00 app[web.1]: 10.179.235.253 - - [18/Mar/2017 09:44:54] "GET /alexa/stream/Tazlwyae6couyno5qs5aum6jsty HTTP/1.1" 500 -
> 2017-03-18T09:44:54.901182+00:00 app[web.1]: Traceback (most recent call last):
> 2017-03-18T09:44:54.901183+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1994, in __call__
> 2017-03-18T09:44:54.901184+00:00 app[web.1]:     return self.wsgi_app(environ, start_response)
> 2017-03-18T09:44:54.901185+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1985, in wsgi_app
> 2017-03-18T09:44:54.901185+00:00 app[web.1]:     response = self.handle_exception(e)
> 2017-03-18T09:44:54.901186+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1540, in handle_exception
> 2017-03-18T09:44:54.901187+00:00 app[web.1]:     reraise(exc_type, exc_value, tb)
> 2017-03-18T09:44:54.901187+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
> 2017-03-18T09:44:54.901188+00:00 app[web.1]:     raise value
> 2017-03-18T09:44:54.901189+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
> 2017-03-18T09:44:54.901190+00:00 app[web.1]:     response = self.full_dispatch_request()
> 2017-03-18T09:44:54.901190+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
> 2017-03-18T09:44:54.901191+00:00 app[web.1]:     rv = self.handle_user_exception(e)
> 2017-03-18T09:44:54.901191+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
> 2017-03-18T09:44:54.901192+00:00 app[web.1]:     reraise(exc_type, exc_value, tb)
> 2017-03-18T09:44:54.901192+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
> 2017-03-18T09:44:54.901193+00:00 app[web.1]:     raise value
> 2017-03-18T09:44:54.901194+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
> 2017-03-18T09:44:54.901194+00:00 app[web.1]:     rv = self.dispatch_request()
> 2017-03-18T09:44:54.901195+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
> 2017-03-18T09:44:54.901195+00:00 app[web.1]:     return self.view_functions[rule.endpoint](**req.view_args)
> 2017-03-18T09:44:54.901196+00:00 app[web.1]:   File "/app/geemusic/controllers.py", line 9, in redirect_to_stream
> 2017-03-18T09:44:54.901197+00:00 app[web.1]:     stream_url = api.get_google_stream_url(song_id)
> 2017-03-18T09:44:54.901198+00:00 app[web.1]:   File "/app/geemusic/utils/music.py", line 136, in get_google_stream_url
> 2017-03-18T09:44:54.901198+00:00 app[web.1]:     return self._api.get_stream_url(song_id)
> 2017-03-18T09:44:54.901199+00:00 app[web.1]:   File "<decorator-gen-102>", line 2, in get_stream_url
> 2017-03-18T09:44:54.901200+00:00 app[web.1]:     
> 2017-03-18T09:44:54.901200+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gmusicapi/utils/utils.py", line 293, in wrapper
> 2017-03-18T09:44:54.901201+00:00 app[web.1]:     return function(*args, **kw)
> 2017-03-18T09:44:54.901202+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gmusicapi/clients/mobileclient.py", line 367, in get_stream_url
> 2017-03-18T09:44:54.901202+00:00 app[web.1]:     raise NotSubscribed("Store tracks require a subscription to stream.")
> 2017-03-18T09:44:54.901203+00:00 app[web.1]: gmusicapi.exceptions.NotSubscribed: Store tracks require a subscription to stream. (https://goo.gl/v1wVHT)
> 2017-03-18T09:44:55.269505+00:00 heroku[router]: at=info method=POST path="/alexa" host=xxx.herokuapp.com request_id=8bff1ed7-b8dd-4e80-897f-fbcbd4931c94 fwd="54.240.197.74" dyno=web.1 connect=1ms service=30ms status=400 bytes=163 protocol=https
> 2017-03-18T09:44:55.258811+00:00 app[web.1]: 10.37.191.73 - - [18/Mar/2017 09:44:55] "POST /alexa HTTP/1.1" 400 -

I've checked the APP_URL config is set correctly (without a trailing / or alexa).

Therefore, a couple of questions:
1) What's actually meant to work when using the free Google Music?
2) What else can I check to further debug this?

Thanks in advance.

**Comment by digiltd** [comment]
Are you trying to play uploaded music?

See #57

**Comment by AGT89** [comment]
Thanks for the quick reply.

Yes I am trying to play uploaded music. I had already ready through #57 - is it saying that playing uploaded music is supported but is likely to be error prone due to the fuzzy matching? Or that is doesn't work at all?

If that's the case, any idea why they generic "play my library" doesn't work? Presumably in that case it shouldn't need to do any fuzzy matching so should play something?

**Comment by digiltd** [comment]
I'm not 100% sure. It seems the "play my library" intent should do what we want, but I haven't got it to work either. I did create a new account for the trial and that worked fine.

I kinda hopeful that eventually it will be worked out. I use Google Music on the free account with Logitech Media Server (with a plugin that is using the same gmusicapi that this skill uses). It lets me search and browse like normal (though not by voice).

**Comment by AGT89** [comment]
That's a shame, hopefully it'll get sorted eventually.

Might be worth adding something to the readme explaining what works and what doesn't with the free Google Music.

**Comment by digiltd** [comment]
True, though I am not sure myself as other (i.e. @PostsDesert) seem to have had success with it

**Comment by and3rson** [comment]
> raise NotSubscribed("Store tracks require a subscription to stream.")

I've had this issue as well. It happens when a user doesn't have a subscription, but is trying to play some uploaded or purchased tracks.

I fixed this by using the following logic in my code:

```python
if mobile_client.is_subscribed:
    track_id = track.storeId  # (or track_id.id)
else:
    track_id = track.id  # TODO: Handle missing "id"
mobile_client.get_stream_url(track_id)
```

The deal here is that most tracks have `id` (library ID) and `storeId` (store ID). To play purchased tracks, you need to pass the library ID (`id`) to `get_stream_url`, **NOT** the `storeId`.

**Comment by and3rson** [comment]
Possibly related: and3rson/clay#3

**Comment by stevenleeg** [comment]
This hasn't seen any recent activity and will therefore be closed. Feel free to comment or file a new issue if you're still having trouble.

**Comment by Schnabelriechen** [comment]
Same error still exist... Playing uploaded contetnt fails.
