### ISSUE TITLE
"Can't find that song"

### ISSUE THREAD

**Issue by SinglePaper** [stevenleeg/geemusic#81]
It says that it can't find the song/artist/playlist, even if I use the examples.

12:05:59 web.1  | 127.0.0.1 - - [08/Apr/2017 12:05:59] "POST /alexa HTTP/1.1" 200 -
12:09:08 web.1  | 127.0.0.1 - - [08/Apr/2017 12:09:08] "POST /alexa HTTP/1.1" 200 -
12:09:18 web.1  | 127.0.0.1 - - [08/Apr/2017 12:09:18] "POST /alexa HTTP/1.1" 200 -
12:09:57 web.1  | 127.0.0.1 - - [08/Apr/2017 12:09:57] "POST /alexa HTTP/1.1" 200 -
12:10:09 web.1  | --------------------------------------------------------------------------------
12:10:09 web.1  | DEBUG in selection [/home/pi/geemusic/geemusic/intents/selection.py:85]:
12:10:09 web.1  | Fetching song hello by Adele
12:10:09 web.1  | --------------------------------------------------------------------------------
12:10:09 web.1  | 127.0.0.1 - - [08/Apr/2017 12:10:09] "POST /alexa HTTP/1.1" 200 -

**Comment by Levynger** [comment]
Having the same problem..  using heroku though.. 

`2017-04-08T18:22:58.660803+00:00 app[web.1]: DEBUG in selection [/app/geemusic/intents/selection.py:85]:
2017-04-08T18:22:58.660804+00:00 app[web.1]: Fetching song the song nothing else matters by Metallica
2017-04-08T18:22:58.660816+00:00 app[web.1]: --------------------------------------------------------------------------------
2017-04-08T18:22:58.984490+00:00 heroku[router]: at=info method=POST path="/alexa" host=pure-mesa-83757.herokuapp.com request_id=eadd34b7-4e23-4edf-9f37-dcf586c78e1e fwd="72.21.217.165" dyno=web.1 connect=2ms service=361ms status=200 bytes=322 protocol=https
2017-04-08T18:22:58.980428+00:00 app[web.1]: 10.158.160.96 - - [08/Apr/2017 18:22:58] "POST /alexa HTTP/1.1" 200 -`

**Comment by stevenleeg** [comment]
Are these songs that are in your personal library (eg you uploaded them from your computer) or the gmusic library?

**Comment by Levynger** [comment]
Yes.
all uploaded from my computer to Google music.. 
i understand it is not supported? only subscribed user to google music will work?

**Comment by SinglePaper** [comment]
I tried both of them, but none worked

**Comment by leaskovski** [comment]
Question, what would happen if you uploaded that song to your library, but then also had a subscription as well?  Would that then fail?

**Comment by snapperheadjoe** [comment]
I have a free GPlay account and I setup the Heroku Gee Music server tonight.  I found the same issue everyone is stating in all these posts.  Echo Dot will not play any music regardless or artist, album or song.  However I found that it will play playlists.  It will play any playlist I have in my library.  However you are limited to 1000 songs per playlist so you can't just dump your whole collection into one playlist (I have 14103 songs in mine).  Also it will just play the playlist in order you can't tell it to shuffle a playlist, at least I haven't found the correct syntax to have Alexa do it.  So I just created pre-shuffled playlists of the songs and albums I want to listen to.  It requires some manual work inside to GPlay music.  Now I say " Alexa, ask Gee Music to play George Michael Shuffle playlist" and it starts playing all my GM songs.  If there is a way to get it to play songs directly from my library without going through the playlist creation that would be great.  Does anyone have any advise on how to do that.  Is this an issue only happening on the Heroku server setup or does this occur with the free Gplay accounts using other servers like PI3, Docker etc?

**Comment by howesda** [comment]
I have exactly the same symptoms as snapperheadjoe when running this on Heroku- but not the python skills to debug it unfortunately.Is there a solution? Or at least a diagnosis?

**Comment by rhortal** [comment]
Same here: playlists seem to work, but not uploaded music directly

**Comment by chaseface777** [comment]
I'm having the exact same problem using Heroku. Anyone have any ideas?

**Comment by fergyfresh** [comment]
Closing in favor of #145.
