### ISSUE TITLE
Alexa responds, but no music is played...used to work

### ISSUE THREAD

**Issue by JVTEAM** [stevenleeg/geemusic#86]
Here's the test log

  "session": {
    "sessionId": "SessionId.3668e119-0805-49bf-a9ce-c21608226bea",
    "application": {
      "applicationId": "amzn1.ask.skill.aab7e4ca-6673-4fa2-8ae5-924f85902e50"
    },
    "attributes": {},
    "user": {
      "userId": "amzn1.ask.account.AGEXVW63FRWHVWQVTXVTBNGA4VXN2LTPC3VETJYH6XA6CA7VDTCPATNZ3X53QM7TGK35HX6MZLLEKUNNP6CFDA2DYMQWJNMV27D7SFPEBPC2YUUCOM6NTEOPWFZRBIFVH2RG5M74AXG5ZSNFENRFH3W2WY6J3XTI2DFU3HPZMAIDTZ4YNKSS6YYEW3VDVOYWX7VVW6XBXULQW5Y"
    },
    "new": true
  },
  "request": {
    "type": "IntentRequest",
    "requestId": "EdwRequestId.87fd28a6-4ad3-407a-9c71-c165998a3b13",
    "locale": "en-US",
    "timestamp": "2017-04-20T19:10:43Z",
    "intent": {
      "name": "GeeMusicPlayArtistIntent",
      "slots": {
        "artist_name": {
          "name": "artist_name",
          "value": "smashing pumpkins"
        }
      }
    }
  },
  "version": "1.0"
}

{
  "version": "1.0",
  "response": {
    "outputSpeech": {
      "type": "PlainText",
      "text": "Playing top tracks from The Smashing Pumpkins"
    },
    "shouldEndSession": true
  },
  "sessionAttributes": {}
}

**Comment by wd5gnr** [comment]
I had this problem when trying to run through a remote proxy (pagekite) where the proxy endpoint and the server were both local to the Alexa. I am not sure if that was the problem or if it was the self signed cert. I went to my "proper" SSL site (that is, a "real" cert and outside my premise) and just pointed it back to my local server using Apache mod_proxy and it worked. So I don't know if it was the cert construction or NAT getting confused.  The symptoms were the same, though: It would identify the playlist or whatever, say it was playing and then nothing.
