### ISSUE TITLE
Unsuccessful login. Aborting!

### ISSUE THREAD

**Issue by DandiC** [stevenleeg/geemusic#88]
Hello,

I'm trying to setup Geemusic in a Ubuntu instance that I set up with Amazon EC2. I follow all the installation steps and when I run the command `foreman start`, I get the following output:

22:47:08 web.1  | started with pid 19651
22:47:09 web.1  |/home/ubuntu/.local/lib/python3.5/sitepackages/Cryptodome/Math/_Numbers_gmp.py:230: UserWarning: implicit cast to 'char *' from a different pointer type: will be forbidden in the future (check that the types are as you expect; use an explicit ffi.cast() if they are correct)
22:47:09 web.1  |   _gmp.gmp_snprintf(buf, c_size_t(buf_len), b("%Zd"), self._mpz_p)
22:47:09 web.1  | Traceback (most recent call last):
22:47:09 web.1  |   File "server.py", line 1, in <module>
22:47:09 web.1  |     from geemusic import app
22:47:09 web.1  |   File "/home/ubuntu/geemusic/geemusic/__init__.py", line 13, in <module>
22:47:09 web.1  |     api = GMusicWrapper.generate_api(logger=app.logger)
22:47:09 web.1  |   File "/home/ubuntu/geemusic/geemusic/utils/music.py", line 257, in generate_api
22:47:09 web.1  |     **kwargs)
22:47:09 web.1  |   File "/home/ubuntu/geemusic/geemusic/utils/music.py", line 17, in __init__
22:47:09 web.1  |     raise Exception("Unsuccessful login. Aborting!")
22:47:09 web.1  | Exception: Unsuccessful login. Aborting!
22:47:10 web.1  | exited with code 1
22:47:10 system | sending SIGTERM to all processes

I've checked that my Google email and password are correct and the server is running with a SSL protocol. I would like to know If someone knows what could be causing the error.

Thanks in advance!

**Comment by DandiC** [comment]
Nevermind, I got to solve the issue creating a generated password for my app.

**Comment by Abhiseshan** [comment]
@DandiC which app did you generate the password for?
