### ISSUE TITLE
Some Playlists throw some sort of album art error

### ISSUE THREAD

**Issue by wd5gnr** [stevenleeg/geemusic#89]
Mostly working but some playlists won't play due to this:

 File "/home/alw/geemusic/geemusic/intents/selection.py", line 149, in play_playlist
 thumbnail = api.get_thumbnail(queue.current_track()['albumArtRef'][0]['url'])
KeyError: 'albumArtRef'

The Playlist appears to have no album art, so this isn't especially surprising but it makes it impossible to play.

Update. I put in code in selection.py to catch any exceptions and set thumbnail to "" Then everywhere a standard card was set up, if thumbnail was "" I instead did a simple card. So basically, a lot of cut and paste of this:

~~~
    try:
        thumbnail = api.get_thumbnail(artist['artistArtRef'])
    except:
        thumbnail = ""
    speech_text = "Playing top tracks by %s" % artist['name']
    if (thumbnail==""):
        return audio(speech_text).play(stream_url) \
                                 .standard_card(title=speech_text,
                                                text='',
                                                small_image_url=thumbnail,
                                                large_image_url=thumbnail)
    else:
        return audio(speech_text).play(stream_url) \
         .simple_card(title=speech_text, content='')
~~~

This got the first song of one playlist to play. But then it didn't go to the 2nd song. That could be an unrelated problem. I can do a pull request on what I have (warning, I'm not much of a Python guy -- I do C++ and many other languages but not a lot of Python). However, I am not sure if the second song problem is related or not. It doesn't seem like it should be.

**Comment by britchris1** [comment]
I believe I have found a workaround for this:
Out of my 20 playlists only 3 would play. For the rest, Alexa would respond "there was an error with this skills response" after some digging I realized that the playlists giving this error all started with a track missing the album art. I re-ordered the list and as long as the first track has album art it plays every time. You can skip through the playlist even if the rest of the songs are missing album art with no issues.

**Comment by fergyfresh** [comment]
Playing it on an echo I personally don't even care about the thumbnail. Wanna just use a default image for everything that doesn't have an image?

**Comment by britchris1** [comment]
yeah that works for me - easy to bulk update?

**Comment by fergyfresh** [comment]
That was part of the reason why the free playlists didn't work. I have a fork with a branch called free that I started to do exactly this.

**Comment by wd5gnr** [comment]
@britchris.com I think my fork should fix that. It essentially makes a default card icon for anything missing art.

**Comment by britchris1** [comment]
Thanks I will give that a try!
