### ISSUE TITLE
How to start geemusic server without Foreman

### ISSUE THREAD

**Issue by megamalain** [stevenleeg/geemusic#94]
You mentioned using foreman to start geemusic server, but how do you do so without it? When I attempt to run (.venv)pi@RaspberryPiBplus:~/geemusic $ python3 server.py
I get the error:

Traceback (most recent call last):
  File "server.py", line 1, in <module>
    from geemusic import app
  File "/home/pi/geemusic/geemusic/__init__.py", line 13, in <module>
    api = GMusicWrapper.generate_api(logger=app.logger)
  File "/home/pi/geemusic/geemusic/utils/music.py", line 256, in generate_api
    return cls(environ['GOOGLE_EMAIL'], environ['GOOGLE_PASSWORD'],
  File "/usr/lib/python3.4/os.py", line 633, in __getitem__
    raise KeyError(key) from None
KeyError: 'GOOGLE_EMAIL'

I have created a .env in my /home/pi folder with values for GOOGLE_EMAIL, GOOGLE_PASSWORD, and APP_URL

**Comment by stevenleeg** [comment]
Foreman is used to inject the variables defined in `.env` into the environment of Geemusic's process. If you'd like to avoid using it you'll need to export those variables before running server.py; something like

`export GOOGLE_EMAIL=someone@gmail.com`.
