### ISSUE TITLE
Next Song Autoplay Hitch

### ISSUE THREAD

**Issue by DocCheese** [stevenleeg/geemusic#95]
Recently when I have it play from a playlist it will not auto-play the next song, I have to tell it "next" to get to the next track. Same if I ask it to play track by an artist.

Originally it was playing consecutively, but now it hitches. 

Nothing to my knowledge has changed server site.

Running Ubuntu on a Digital Ocean Droplet connected to a Heroku free account.

Any thoughts?

**Comment by WaferMouse** [comment]
We are having exactly the same issues with Plexmusic, but nobody over there has been able to resolve it either yet. When you tell it to play the next track, does it skip a track? Eg. If you listen to track 1 then have to say "next", does it play track 3?

**Comment by WaferMouse** [comment]
Also, how frequent is this? Is it every time or only most of the time?

**Comment by compmas2** [comment]
I just setup geemusic for the first time and I am having this same issue when playing music on a playlist I have configured.  If I tell it to skip a song, the next song plays and then playback stops.  When I ask Alexa to play the next song, it states that that command only works when playing music.  This must mean the playback stopped.  This does not happen every time I skip a song.

**Comment by fergyfresh** [comment]
Seems to be a solved issue with `gmusicapi`.
