### ISSUE TITLE
Can't play artist 'Tool'? No support for non-streaming artists in own uploaded albums?

### ISSUE THREAD

**Issue by mycol** [stevenleeg/geemusic#99]
My current setup:
foreman (port 5000) + ngrok
google music w/ free trail of music subscription

I'm able to stream my albums but when I try to play any song by Tool I'm told it can't find that artist even though I uploaded the Tool albums I own. I assume this is due to the lack of streaming contracts with Google music by the artist but I could be mistaken. Has anyone else run into an issue like this? I believe Taylor Swift and a few others don't stream so I wonder if those uploaded albums would be affected. 

I wonder what will happen when my trial to google's subscription services end.

**Comment by Danondso** [comment]
I have a couple Tool albums that I tried to stream myself. At the time I gave up trying to get it to work but I recall reading somewhere you can specify songs from your library (at least with gmusicapi). Maybe try to query by specifying that you want to stream from your library? Not sure beyond that :(

**Comment by mycol** [comment]
I'll see if I can specify tracks from my own library, thanks for the suggestion!

**Comment by fergyfresh** [comment]
Closing in favor of #145.
